#!/usr/bin/env node
import {createHash,createPublicKey,verify} from 'node:crypto';
import {cpSync,existsSync,linkSync,mkdirSync,readFileSync,renameSync,rmSync,writeFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {canonical,canonicalSha256,PHASE2_CAPABILITIES,renderPhase2InstallPromptCore,validateBuildSelection,validatePhase2TestReport,verifySelectionCheckout} from './phase2-gate.mjs';
import {createPhase2CapabilityManifest,assembleManagedUpdater,verifyPhase2CandidateBuildIdentity,verifyPhase2CapabilityClosure,verifyPhase2SignedClosure} from '../build/assemble.mjs';
import {phase2ArtifactPreflight,renderPhase2ExternalInstallPrompt,validatePhase2ArtifactReceipt,validatePhase2InstallPrompt} from './preflight.mjs';
import {preflightReleaseEnvironment} from './release-environment.mjs';
import {signReleaseFile} from './trust.mjs';
import {phase2ArchiveProof} from './verify-availability.mjs';
import {hashBuildInputs} from '../dev/runtime.mjs';

const root=resolve(fileURLToPath(new URL('../..',import.meta.url))),sha=value=>createHash('sha256').update(value).digest('hex');
function fail(code='PHASE2_ASSEMBLY_INVALID'){throw new Error(code);}
export function phase2ClosureBytes(value){return Buffer.from(canonical(value));}
/** @param {unknown} selectionInput @param {{projectRoot?:string,runBuild?:(file:string,args:readonly string[],options:import('node:child_process').ExecFileSyncOptions)=>unknown}} [options] */
export function preparePhase2CandidateBuild(selectionInput,{projectRoot=root,runBuild=execFileSync}={}){
  const selection=validateBuildSelection(selectionInput),buildScript=join(projectRoot,'scripts/build/build.mjs');
  runBuild(process.execPath,[buildScript],{cwd:projectRoot,env:{...process.env,AUTOED_RELEASE_VERSION:selection.version},stdio:'pipe',timeout:120000,maxBuffer:1024*1024});
  const build=JSON.parse(readFileSync(join(projectRoot,'build/identity.json'),'utf8'));
  verifyPhase2CandidateBuildIdentity(selection,build);
  return build;
}
function descriptor(tag,path,extra={}){const bytes=readFileSync(path),name=path.slice(path.lastIndexOf('/')+1);return{name,localPath:path.slice(root.length+1),url:`https://github.com/returdex/AutoED/releases/download/${tag}/${encodeURIComponent(name)}`,bytes:bytes.length,sha256:sha(bytes),...extra};}
function localAssetMap(target){return new Map([target,target.updater.bootstrap,target.updater.manifest,target.updater.signature,...target.updater.artifacts].map(asset=>[asset.name,readFileSync(join(root,asset.localPath))]));}
async function assemble(){
  const selection=validateBuildSelection(JSON.parse(readFileSync(join(root,'release/phase2-build-selection.json'),'utf8'))),tests=validatePhase2TestReport(JSON.parse(readFileSync(join(root,'release/phase2-test-report.json'),'utf8')),selection),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),tree=execFileSync('git',['rev-parse','HEAD^{tree}'],{cwd:root,encoding:'utf8'}).trim();verifySelectionCheckout(selection,{commit:head,tree,sourceSha256:hashBuildInputs(root)});
  const versionRoot=join(root,'.runtime/releases',selection.version),receiptPath=join(root,'release/phase2-beta-artifacts.json'),promptPath=join(root,'release/phase2-install-prompt.md');if(existsSync(versionRoot)||existsSync(receiptPath)||existsSync(promptPath))fail('PHASE2_ASSEMBLY_OUTPUT_EXISTS');
  await preflightReleaseEnvironment({root});preparePhase2CandidateBuild(selection,{projectRoot:root});
  mkdirSync(versionRoot,{recursive:true,mode:0o700});const transient=join(versionRoot,'.assembly');mkdirSync(transient,{mode:0o700});const trustRoot=JSON.parse(readFileSync(join(root,'release/trust-root.json'),'utf8'));
  const packageTarget=async(token,platform)=>{const work=join(transient,token),assembled=await assembleManagedUpdater({projectRoot:root,targetRoot:work,target:token,selection,testReport:tests});for(const item of [assembled.updater.bootstrap,assembled.updater.manifest,assembled.updater.signature,...assembled.updater.artifacts])renameSync(join(root,item.localPath),join(versionRoot,item.name));const program=join(assembled.delivery.root,'program'),closure=createPhase2CapabilityManifest({root:program,selection,testReport:tests}),closureBytes=phase2ClosureBytes(closure),closureSha256=sha(closureBytes),core=readFileSync(join(program,'phase2/install-prompt-core.md')),manifest={schema:1,selectionSha256:canonicalSha256(selection),testReportSha256:canonicalSha256(tests),capabilityClosureSha256:closureSha256,installPromptCoreSha256:sha(core),fingerprint:trustRoot.fingerprint,license:selection.license},manifestPath=join(work,'phase2-manifest.json'),signaturePath=join(work,'phase2-manifest.sig');writeFileSync(manifestPath,canonical(manifest),{flag:'wx',mode:0o600});await signReleaseFile({publicPath:join(root,'release/trust-root.json'),inputPath:manifestPath,outputPath:signaturePath});const outer=join(work,'outer');mkdirSync(join(outer,'phase2'),{recursive:true,mode:0o700});cpSync(program,join(outer,'program'),{recursive:true,dereference:false,verbatimSymlinks:true});writeFileSync(join(outer,'phase2/capability-closure.json'),closureBytes,{flag:'wx',mode:0o600});cpSync(manifestPath,join(outer,'phase2/manifest.json'));cpSync(signaturePath,join(outer,'phase2/manifest.sig'));const outerName=`autoed-${selection.version}-${token}-capability.tar.gz`,outerPath=join(versionRoot,outerName);execFileSync('/usr/bin/tar',['-czf',outerPath,'--format','ustar','-C',outer,'phase2','program'],{env:{...process.env,COPYFILE_DISABLE:'1'},stdio:'pipe',timeout:600000});const key=createPublicKey(trustRoot.publicKey),manifestBytes=readFileSync(manifestPath),signature=readFileSync(signaturePath);if(!verify(null,manifestBytes,key,signature))fail('PHASE2_ASSEMBLY_SIGNATURE_INVALID');verifyPhase2SignedClosure({bytes:manifestBytes,signature,expectedFingerprint:trustRoot.fingerprint,selection,testReport:tests,closure,verifyManifest:()=>({fingerprint:trustRoot.fingerprint,selectionSha256:canonicalSha256(selection),testReportSha256:canonicalSha256(tests),capabilityClosureSha256:closureSha256})});const updater={bootstrap:descriptor(selection.tag,join(versionRoot,assembled.updater.bootstrap.name)),manifest:descriptor(selection.tag,join(versionRoot,assembled.updater.manifest.name)),signature:descriptor(selection.tag,join(versionRoot,assembled.updater.signature.name)),artifacts:assembled.updater.artifacts.map(item=>descriptor(selection.tag,join(versionRoot,item.name),{role:item.role}))};return{platform,program,closure,manifest,outer:{...descriptor(selection.tag,outerPath),manifestSha256:sha(manifestBytes),signatureSha256:sha(signature),capabilityClosureSha256:closureSha256,updater}};};
  try{const mac=await packageTarget('darwin-arm64','macos'),windows=await packageTarget('win32-x64','windows');if(canonicalSha256(mac.closure)!==canonicalSha256(windows.closure))fail('PHASE2_ASSEMBLY_CLOSURE_MISMATCH');verifyPhase2CapabilityClosure({selection,testReport:tests,targets:{macos:{root:mac.program,manifest:mac.closure},windows:{root:windows.program,manifest:windows.closure}}});const draft={schema:1,status:'built_signed_verified_local',owner:'returdex',repository:'returdex/AutoED',repositoryId:1350421724,version:selection.version,tag:selection.tag,commit:selection.commit,tree:selection.tree,buildId:selection.buildId,selectionSha256:canonicalSha256(selection),testReportSha256:canonicalSha256(tests),sourceSha256:selection.sourceSha256,versionSetSha256:selection.versionSetSha256,manifestSha256:sha(Buffer.from(canonical({macos:mac.manifest,windows:windows.manifest}))),fingerprint:trustRoot.fingerprint,license:selection.license,immutable:true,installPromptCoreSha256:sha(renderPhase2InstallPromptCore(selection,tests)),externalPromptSha256:'0'.repeat(64),capabilitiesSha256:canonicalSha256(PHASE2_CAPABILITIES),targets:{macos:mac.outer,windows:windows.outer},gaps:selection.gaps},prompt=renderPhase2ExternalInstallPrompt(draft),receipt={...draft,externalPromptSha256:sha(prompt)};validatePhase2ArtifactReceipt(receipt,{selection,testReport:tests});validatePhase2InstallPrompt(prompt,receipt);for(const platform of ['macos','windows'])phase2ArchiveProof(platform,localAssetMap(receipt.targets[platform]),receipt);writeFileSync(receiptPath+'.tmp',canonical(receipt)+'\n',{flag:'wx',mode:0o600});linkSync(receiptPath+'.tmp',receiptPath);rmSync(receiptPath+'.tmp');writeFileSync(promptPath+'.tmp',prompt,{flag:'wx',mode:0o600});linkSync(promptPath+'.tmp',promptPath);rmSync(promptPath+'.tmp');const checked=phase2ArtifactPreflight(receiptPath,promptPath,{root});return{status:'pass',version:receipt.version,assets:16,preflight:checked.status,offlineTargetProof:'pass'};}finally{rmSync(transient,{recursive:true,force:true});}
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))assemble().then(value=>process.stdout.write(JSON.stringify(value)+'\n')).catch(error=>{process.stderr.write(`${/^PHASE2_[A-Z0-9_]+$/.test(error?.message??'')?error.message:'PHASE2_ASSEMBLY_FAILED'}\n`);process.exitCode=1;});
