import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {copyFileSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),runtime=join(root,'.runtime/releases'),sha=b=>createHash('sha256').update(b).digest('hex'),pair=JSON.parse(readFileSync(join(runtime,'pair.json'))),fingerprint=pair.fingerprint;
function descriptor(version,path,name){const bytes=readFileSync(path);return{name,url:`https://github.com/returdex/AutoED/releases/download/${version}/${name}`,bytes:bytes.length,sha256:sha(bytes),localPath:path.slice(root.length+1)};}
const versions=[...new Set(pair.releases.map(r=>r.version))].sort((a,b)=>Number(a.split('.').at(-1))-Number(b.split('.').at(-1)));if(versions.length!==2||!versions.every(v=>/^0\.1\.0-beta\.[1-9]\d*$/.test(v))||Number(versions[1].split('.').at(-1))!==Number(versions[0].split('.').at(-1))+1)throw new Error('VERSION_INVALID');
const releases=[];
for(const [index,version] of versions.entries()){const folder=join(runtime,version),targets=pair.releases.filter(r=>r.version===version),shared=[];if(targets.length!==2||targets.some(t=>t.variant!==(index===0?'A':'B')))throw new Error('RELEASE_PAIR_INVALID');for(const name of ['LICENSE','LICENSING.md']){copyFileSync(join(root,name),join(folder,name));shared.push(descriptor(version,join(folder,name),name));}
  const sourceName=`autoed-${version}-source.tar.gz`,sourcePath=join(folder,sourceName);execFileSync('git',['archive','--format=tar.gz','-o',sourcePath,'HEAD'],{cwd:root,stdio:'pipe'});shared.push(descriptor(version,sourcePath,sourceName));
  const blocks=targets.map(t=>{const bootstrap=t.assets.find(a=>a.name===t.bootstrapName),platform=t.target==='darwin-arm64'?'macOS 14+（Apple Silicon）':'Windows 11 x64',stage=t.target==='darwin-arm64'?'$HOME/Library/Caches/AutoED-Rebuild-M1':'$env:LOCALAPPDATA\\AutoED-Rebuild-M1-Staging',install=t.target==='darwin-arm64'?'$HOME/Library/Application Support/AutoED-Rebuild-M1':'$env:LOCALAPPDATA\\AutoED-Rebuild-M1',command=t.target==='darwin-arm64'?`mkdir -p "${stage}" && chmod 700 "${stage}"\ncurl -fL --proto '=https' -o autoed-bootstrap.sh '${bootstrap.url}'\necho '${bootstrap.sha256}  autoed-bootstrap.sh' | shasum -a 256 -c -\n/bin/sh autoed-bootstrap.sh --staging-parent "${stage}"`:`New-Item -ItemType Directory -Force -Path "${stage}" | Out-Null\nInvoke-WebRequest -UseBasicParsing -Uri '${bootstrap.url}' -OutFile .\\autoed-bootstrap.ps1\nif ((Get-FileHash .\\autoed-bootstrap.ps1 -Algorithm SHA256).Hash.ToLowerInvariant() -ne '${bootstrap.sha256}') { throw 'BOOTSTRAP_HASH_MISMATCH' }\n& .\\autoed-bootstrap.ps1 -StagingParent "${stage}"`;return `### ${platform}\n\n完整 bootstrap SHA-256：\`${bootstrap.sha256}\`  \n固定发布公钥指纹：\`${fingerprint}\`\n\n\`\`\`${t.target==='darwin-arm64'?'sh':'powershell'}\n${command}\n\`\`\`\n\n安装器显示预览时，安装根目录输入：\`${install}\`。核对版本、build ID、保留数据、停机和清理范围后，按屏幕要求输入完整确认短语。不要在聊天中提供密码/MFA；本 beta 不登录课程网站。\n\n安装成功后，CLI 位于 \`${install}${t.target==='darwin-arm64'?'/bin/autoed-rebuild':'\\bin\\autoed-rebuild.cmd'}\`。MCP 注册名固定为 \`autoed-rebuild-m1\`，command 使用该 CLI，args 为 \`["mcp"]\`；重新加载 Codex 后再调用。`;}).join('\n\n');
  const promptName=`autoed-${version}-install.md`,promptPath=join(folder,promptName),previous=index===1?`这是 A→B 更新：先确认当前 ${versions[0]} 可调用 echo，再执行本页 ${version} bootstrap；升级完成必须核对实际 build ID、digest 自检和 cleanup=complete。若 cleanup_pending，保留现场并停止测试。`:`这是首次安装 ${version}：只验证 echo；不要尝试 digest。`;
  writeFileSync(promptPath,`# AutoED ${version} 安装与更新提示\n\n${previous}\n\n发布根：\`returdex/AutoED\`；许可为 PolyForm Noncommercial 1.0.0。Windows 产物只有静态闭包证据，原生运行仍为 not_run。\n\n${blocks}\n\n## 更新与人工测试顺序\n\n1. 在对应原生系统执行本页命令并完成安装器预览确认。\n2. 运行 CLI \`status\` 与 \`selftest --kind echo --value beta\`；${versions[1]} 再运行 \`selftest --kind digest --value beta\`。\n3. 核对 MCP 注册、重载 Codex、调用 \`autoed_status\`；不得把 beta 发布本身当作人工通过。\n4. 发现旧入口、旧受管进程、build 不一致或 \`cleanup_pending\` 时立即停止，不开始登录。\n`);shared.push(descriptor(version,promptPath,promptName));
  releases.push({version,variant:targets[0].variant,commit:targets[0].build.commit,tree:targets[0].build.tree,buildId:targets[0].build.buildId,capabilities:targets[0].build.capabilities,targets:targets.map(t=>({target:t.target,buildId:t.build.buildId,manifest:t.manifestName,signature:t.signatureName,bootstrap:t.bootstrapName,evidence:{synthetic:'pass',integration:'pass',macosNative:t.target==='darwin-arm64'?'pass':'not_run',windowsNative:'not_run',human:'not_run'},assets:t.assets.map(a=>({...a,localPath:a.path.slice(root.length+1)}))})),shared});
}
const output={schema:1,status:'built_signed_verified_local',repository:'returdex/AutoED',fingerprint,versions:releases,windowsNative:'not_run',humanUAT:'not_run',stableClaim:false};mkdirSync(join(root,'release'),{recursive:true});writeFileSync(join(root,'release/beta-artifacts.json'),JSON.stringify(output,null,2)+'\n');writeFileSync(join(root,'release/install-prompts.md'),releases.map(r=>readFileSync(join(runtime,r.version,`autoed-${r.version}-install.md`),'utf8')).join('\n\n---\n\n'));process.stdout.write(JSON.stringify({status:'pass',versions:releases.map(r=>r.version),assets:releases.reduce((n,r)=>n+r.shared.length+r.targets.reduce((m,t)=>m+t.assets.length,0),0)})+'\n');
