import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {lstatSync,readFileSync,readdirSync,realpathSync} from 'node:fs';
import {homedir} from 'node:os';
import {dirname,join,relative,isAbsolute,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {PHASE2_CAPABILITIES,canonicalSha256,validateBuildSelection,validatePhase2TestReport} from './phase2-gate.mjs';
import {hashBuildInputs} from '../dev/runtime.mjs';

const repo=join(dirname(fileURLToPath(import.meta.url)),'../..'),allowedNames=new Set(['LICENSE','LICENSING.md']),allowedRoots=new Set(['dist','runtime','browser','public-manifest','bootstrap','docs']),sourceRoots=new Set(['.planning','apps','docs','packages','rebuild-2026-08-26','release','scripts','tests']),sourceFiles=new Set(['.gitignore','AGENTS.md','LICENSE','LICENSING.md','package-lock.json','package.json','playwright.config.ts','tsconfig.json','vitest.config.ts']),forbidden=/(?:^|\/)(?:Profile|Cookies?|.*\.sqlite(?:-wal|-shm)?|\.env(?:\..*)?|logs?|private[-_]?keys?|private[-_]?fixtures?)(?:\/|$)/i,secret=new RegExp(['gh'+'[pousr]_[A-Za-z0-9]{20,}','github_'+'pat_[A-Za-z0-9_]{20,}','-----BEGIN '+'(?:OPENSSH|EC|RSA|PRIVATE) PRIVATE KEY-----','CANARY_'+'RELEASE_SECRET'].join('|'));
const reviewedFixtures=new Map([
  ['cef27bea75b9b60bd08288674cf66fcbe3e14518',{path:'scripts/release/preflight.mjs',reason:'reviewed-detector-source'}],
  ['90eaa763d659068307640c66381003243a47cc0c',{path:'tests/integration/release-gates.test.ts',reason:'reviewed-negative-fixture'}],
  ['2624b58ba44aa0c961c04f58421964ed8e56d127',{path:'tests/integration/release-gates.test.ts',reason:'reviewed-negative-fixture'}],
]);
const digest=value=>createHash('sha256').update(value).digest('hex');
function reject(code){throw new Error(code);}
function approvedEmail(value){return /^\d+\+returdex@users\.noreply\.github\.com$/.test(value);}
export function isReviewedFixtureException(hash,path){const item=reviewedFixtures.get(hash);return !!item&&item.path===path&&(path==='scripts/release/preflight.mjs'||path==='tests/integration/release-gates.test.ts');}

export function assertReleaseIdentity(value){
  if(value?.authorName!=='returdex'||value?.committerName!=='returdex'||!approvedEmail(value.authorEmail)||!approvedEmail(value.committerEmail)||value.login!=='returdex'||value.repository?.owner!=='returdex'||value.repository?.name!=='AutoED')reject('RELEASE_IDENTITY_MISMATCH');
  if(value.repository.exists&&!(value.repository.creationReceipt?.schema===1&&value.repository.creationReceipt?.plan==='01-12'&&value.repository.creationReceipt?.owner==='returdex'&&value.repository.creationReceipt?.name==='AutoED'&&value.repository.creationReceipt?.status==='approved'))reject('REPOSITORY_CONFLICT');
  return Object.freeze({owner:'returdex',repository:'AutoED'});
}
function exactKeys(value,keys){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join(',')===[...keys].sort().join(',');}
export function validatePrerequisites(value){
  if(!exactKeys(value,['schema','plan','status','checkedAt','approvalSha256','fingerprint','fingerprintUserConfirmed','osKeyAvailable','isolatedLogin','globalLoginObserved','isolatedConfigProtection','localGit','repository','localRemoteConfigured'])||value.schema!==1||value.plan!=='01-12'||value.status!=='approved'||!/^2026-08-29T\d{2}:\d{2}:\d{2}Z$/.test(value.checkedAt)||!/^[a-f0-9]{64}$/.test(value.approvalSha256)||!/^[a-f0-9]{64}$/.test(value.fingerprint)||value.fingerprintUserConfirmed!==true||value.osKeyAvailable!==true||value.isolatedLogin!=='returdex'||value.globalLoginObserved!=='ywan1303'||value.isolatedConfigProtection!=='0700'||value.localRemoteConfigured!==false||!exactKeys(value.localGit,['authorName','committerName','authorEmail','committerEmail'])||!exactKeys(value.repository,['owner','name','exactNameExists','canonicalObserved','state'])||value.repository.owner!=='returdex'||value.repository.name!=='AutoED'||value.repository.exactNameExists!==false||value.repository.state!=='available_after_user_rename'||value.repository.canonicalObserved==='returdex/AutoED')reject('RELEASE_PREREQUISITES_INVALID');
  assertReleaseIdentity({...value.localGit,login:value.isolatedLogin,repository:{owner:value.repository.owner,name:value.repository.name,exists:value.repository.exactNameExists,creationReceipt:null}});return Object.freeze(value);
}
export function assertVersionAvailable(version,existing=[]){const match=/^0\.1\.0-beta\.(\d+)$/.exec(version);if(!match||!Number.isSafeInteger(Number(match[1]))||Number(match[1])<1)reject('VERSION_INVALID');const numbers=existing.map(x=>/^0\.1\.0-beta\.(\d+)$/.exec(x)).filter(Boolean).map(x=>Number(x[1]));if(existing.includes(version)||numbers.some(n=>n>=Number(match[1])))reject('VERSION_ALREADY_EXISTS');return true;}

function scanBytes(bytes){if(bytes.length>64*1024*1024||secret.test(bytes.toString('utf8')))reject('SECRET_SCAN_REJECTED');}
export function scanPublicPackage(root){try{if(!isAbsolute(root)||realpathSync(root)!==root||!lstatSync(root).isDirectory())throw new Error();if(!readFileSync(join(root,'LICENSE')).equals(readFileSync(join(repo,'LICENSE')))||!readFileSync(join(root,'LICENSING.md')).equals(readFileSync(join(repo,'LICENSING.md'))))reject('LICENSE_MISMATCH');let files=0;const walk=(directory,prefix='')=>{for(const entry of readdirSync(directory,{withFileTypes:true})){const rel=prefix+entry.name,path=join(directory,entry.name),stat=lstatSync(path);if(stat.isSymbolicLink()||forbidden.test(rel)||(!prefix&&!allowedNames.has(entry.name)&&!allowedRoots.has(entry.name)))reject('PUBLIC_PACKAGE_REJECTED');if(entry.isDirectory())walk(path,rel+'/');else if(entry.isFile()){if(++files>100000||stat.nlink!==1)reject('PUBLIC_PACKAGE_REJECTED');scanBytes(readFileSync(path));}else reject('PUBLIC_PACKAGE_REJECTED');}};walk(root);return{status:'pass',files};}catch(error){if(error instanceof Error&&['LICENSE_MISMATCH','PUBLIC_PACKAGE_REJECTED','SECRET_SCAN_REJECTED'].includes(error.message))throw error;reject('PUBLIC_PACKAGE_REJECTED');}}

export function scanReachableHistory(root,treeish='HEAD'){
  try{if(!isAbsolute(root)||realpathSync(root)!==root||!/^[A-Za-z0-9._/-]{1,128}$/.test(treeish))throw new Error();const rows=execFileSync('git',['rev-list','--objects',treeish],{cwd:root,encoding:'utf8',timeout:30000,maxBuffer:32*1024*1024}).trim().split('\n').filter(Boolean);let blobs=0,exceptions=0;for(const row of rows){const hash=row.slice(0,40),path=row.length>41?row.slice(41):'';if(!/^[a-f0-9]{40}$/.test(hash))throw new Error();if(execFileSync('git',['cat-file','-t',hash],{cwd:root,encoding:'utf8',timeout:5000}).trim()!=='blob')continue;const top=path.split('/')[0];if(!path||forbidden.test(path)||(!sourceFiles.has(path)&&!sourceRoots.has(top)))reject('SOURCE_HISTORY_REJECTED');if(++blobs>200000)reject('SOURCE_HISTORY_REJECTED');const size=Number(execFileSync('git',['cat-file','-s',hash],{cwd:root,encoding:'utf8',timeout:5000}).trim());if(!Number.isSafeInteger(size)||size<0||size>64*1024*1024)reject('SOURCE_HISTORY_REJECTED');const bytes=execFileSync('git',['cat-file','blob',hash],{cwd:root,timeout:5000,maxBuffer:64*1024*1024+1});try{scanBytes(bytes);}catch(error){if(error instanceof Error&&error.message==='SECRET_SCAN_REJECTED'&&isReviewedFixtureException(hash,path)){exceptions++;continue;}throw error;}}return{status:'pass',blobs,exceptions};}catch{reject('SOURCE_HISTORY_REJECTED');}
}

function shaFile(path){return digest(readFileSync(path));}
export function identityOnly({root=repo,prerequisitesPath=join(repo,'release/prerequisites.json')}={}){
  const value=validatePrerequisites(JSON.parse(readFileSync(prerequisitesPath,'utf8'))),trust=JSON.parse(readFileSync(join(root,'release/trust-root.json'),'utf8')),approval=join(root,'release/approval.json');
  if(shaFile(approval)!==value.approvalSha256||trust.fingerprint!==value.fingerprint||trust.approvalSha256!==value.approvalSha256)reject('RELEASE_PREREQUISITES_INVALID');
  const isolated=process.platform==='darwin'?join(homedir(),'Library/Application Support/AutoED-Rebuild-Release/github'):join(process.env.LOCALAPPDATA??'', 'AutoED-Rebuild-Release/github'),env={...process.env,GH_CONFIG_DIR:isolated};
  if((lstatSync(dirname(isolated)).mode&0o777)!==0o700||(lstatSync(isolated).mode&0o777)!==0o700)reject('RELEASE_IDENTITY_MISMATCH');
  const run=(file,args,options={})=>execFileSync(file,args,{cwd:root,encoding:'utf8',timeout:30000,maxBuffer:1024*1024,...options}).trim();
  const isolatedLogin=run('gh',['api','user','--jq','.login'],{env}),globalLogin=run('gh',['api','user','--jq','.login']);let canonical=null;try{canonical=run('gh',['api','repos/returdex/AutoED','--jq','.full_name'],{env});}catch(error){if(error?.status!==1)throw error;}
  const facts={...value.localGit,login:isolatedLogin,repository:{owner:'returdex',name:'AutoED',exists:canonical==='returdex/AutoED',creationReceipt:null}};
  facts.authorName=run('git',['config','--local','user.name']);facts.committerName=facts.authorName;facts.authorEmail=run('git',['config','--local','user.email']);facts.committerEmail=facts.authorEmail;
  if(globalLogin!==value.globalLoginObserved||canonical!==value.repository.canonicalObserved||run('git',['remote'])!==''||isolatedLogin!==value.isolatedLogin)reject('RELEASE_IDENTITY_MISMATCH');assertReleaseIdentity(facts);return Object.freeze({status:'pass',login:isolatedLogin,fingerprint:value.fingerprint,repository:'returdex/AutoED',exactNameExists:false,globalIdentityUnchanged:true});
}

export function artifactPreflight(path){
  const source=JSON.parse(readFileSync(resolve(path),'utf8'));if(source.schema!==1||source.status!=='built_signed_verified_local'||source.repository!=='returdex/AutoED'||source.fingerprint!==JSON.parse(readFileSync(join(repo,'release/trust-root.json'))).fingerprint||source.versions?.length!==2)reject('RELEASE_ARTIFACTS_INVALID');const head=execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),seen=new Set();let assets=0;
  const numbers=source.versions.map(release=>Number(/^0\.1\.0-beta\.(\d+)$/.exec(release.version)?.[1]));if(numbers.some(n=>!Number.isSafeInteger(n)||n<1)||numbers[1]!==numbers[0]+1)reject('RELEASE_ARTIFACTS_INVALID');
  for(const [index,release] of source.versions.entries()){assertVersionAvailable(release.version,[]);try{execFileSync('git',['merge-base','--is-ancestor',release.commit,head],{cwd:repo,stdio:'ignore'});if(execFileSync('git',['rev-parse',release.commit+'^{tree}'],{cwd:repo,encoding:'utf8'}).trim()!==release.tree)throw new Error();}catch{reject('RELEASE_ARTIFACTS_INVALID');}if(release.variant!==(index===0?'A':'B')||release.targets?.length!==2||release.targets.some(t=>t.buildId!==release.buildId)||release.capabilities.join(',')!==(index===0?'echo':'echo,digest'))reject('RELEASE_ARTIFACTS_INVALID');for(const item of [...release.shared,...release.targets.flatMap(t=>t.assets)]){if(seen.has(release.version+'/'+item.name)||item.url!==`https://github.com/returdex/AutoED/releases/download/${release.version}/${encodeURIComponent(item.name)}`||!item.localPath.startsWith('.runtime/releases/')||isAbsolute(item.localPath))reject('RELEASE_ARTIFACTS_INVALID');seen.add(release.version+'/'+item.name);const bytes=readFileSync(join(repo,item.localPath));if(bytes.length!==item.bytes||digest(bytes)!==item.sha256)reject('RELEASE_ARTIFACTS_INVALID');assets++;}}
  if(assets<30||readFileSync(join(repo,'release/install-prompts.md'),'utf8').includes('UNESTABLISHED'))reject('RELEASE_ARTIFACTS_INVALID');return Object.freeze({status:'pass',head,versions:source.versions.map(v=>v.version),assets,history:scanReachableHistory(repo,'HEAD')});
}

const phase2Hash=/^[a-f0-9]{64}$/;
const phase2Version=/^0\.1\.0-beta\.[1-9]\d*$/;
const phase2Fingerprint='fe7168c33489a34aaac2cefba36bc62bca76f9406a4b7293927a6b7e22201557';
const phase2Private=/(?:^|\/)(?:Profile|Cookies?|.*\.sqlite(?:-wal|-shm)?|\.env(?:\..*)?|logs?|private[-_]?keys?|private[-_]?fixtures?)(?:\/|$)/i;
function phase2Gaps(value){return exactKeys(value,['windowsNative','live','phase3'])&&value.windowsNative==='not_run/human_needed'&&value.live==='not_run/human_needed'&&value.phase3==='blocked';}
function phase2Target(value,platform,version){return exactKeys(value,['name','localPath','url','bytes','sha256','manifestSha256','signatureSha256','capabilityClosureSha256'])&&typeof value.name==='string'&&value.name.includes(platform==='macos'?'darwin-arm64':'win32-x64')&&!phase2Private.test(value.name)&&typeof value.localPath==='string'&&value.localPath.startsWith(`.runtime/releases/${version}/`)&&!isAbsolute(value.localPath)&&!phase2Private.test(value.localPath)&&value.url===`https://github.com/returdex/AutoED/releases/download/v${version}/${encodeURIComponent(value.name)}`&&Number.isSafeInteger(value.bytes)&&value.bytes>0&&phase2Hash.test(value.sha256)&&phase2Hash.test(value.manifestSha256)&&phase2Hash.test(value.signatureSha256)&&phase2Hash.test(value.capabilityClosureSha256);}
export function validatePhase2ArtifactReceipt(value,{selection:selectionInput,testReport:testReportInput}){
  try{
    const selection=validateBuildSelection(selectionInput),testReport=validatePhase2TestReport(testReportInput,selection);
    if(!exactKeys(value,['schema','status','owner','repository','repositoryId','version','tag','commit','tree','buildId','selectionSha256','testReportSha256','sourceSha256','versionSetSha256','manifestSha256','fingerprint','license','immutable','promptSha256','capabilitiesSha256','targets','gaps'])||value.schema!==1||value.status!=='built_signed_verified_local'||value.owner!=='returdex'||value.repository!=='returdex/AutoED'||value.repositoryId!==1350421724||!phase2Version.test(value.version)||value.version!==selection.version||value.tag!==selection.tag||value.commit!==selection.commit||value.tree!==selection.tree||value.buildId!==selection.buildId||value.selectionSha256!==canonicalSha256(selection)||value.testReportSha256!==canonicalSha256(testReport)||value.sourceSha256!==selection.sourceSha256||value.versionSetSha256!==selection.versionSetSha256||!phase2Hash.test(value.manifestSha256)||value.fingerprint!==phase2Fingerprint||value.fingerprint!==selection.trustFingerprint||value.license!=='PolyForm-Noncommercial-1.0.0'||value.immutable!==true||!phase2Hash.test(value.promptSha256)||value.capabilitiesSha256!==canonicalSha256(PHASE2_CAPABILITIES)||!exactKeys(value.targets,['macos','windows'])||!phase2Target(value.targets.macos,'macos',value.version)||!phase2Target(value.targets.windows,'windows',value.version)||value.targets.macos.capabilityClosureSha256!==value.targets.windows.capabilityClosureSha256||!phase2Gaps(value.gaps))reject('PHASE2_ARTIFACTS_INVALID');
    return Object.freeze(value);
  }catch(error){if(error instanceof Error&&error.message==='PHASE2_ARTIFACTS_INVALID')throw error;reject('PHASE2_ARTIFACTS_INVALID');}
}

export function validatePhase2InstallPrompt(text,receipt){
  try{
    if(typeof text!=='string'||Buffer.byteLength(text)<512||Buffer.byteLength(text)>131072||digest(Buffer.from(text))!==receipt.promptSha256||/(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|-----BEGIN (?:OPENSSH|EC|RSA|PRIVATE) PRIVATE KEY-----|\/(?:Users|home)\/[^\s`"']+)/.test(text))throw new Error();
    const required=[receipt.version,receipt.tag,receipt.buildId,receipt.fingerprint,receipt.license,'returdex/AutoED','not_run/human_needed','Phase 3','blocked',...Object.values(receipt.targets).flatMap(target=>[target.name,target.url,String(target.bytes),target.sha256,target.manifestSha256,target.signatureSha256,target.capabilityClosureSha256])];
    if(required.some(value=>!text.includes(value))||!text.includes('cleanup=complete')||!text.includes('不得覆盖')||!text.includes('不得登录')||!text.includes('不得复制或备份 Profile')||!text.includes('不得删除课程资料'))throw new Error();return text;
  }catch{reject('PHASE2_PROMPT_INVALID');}
}

export function phase2ArtifactPreflight(receiptPath,promptPath,{root=repo}={}){
  try{
    const selectionPath=join(root,'release/phase2-build-selection.json'),testReportPath=join(root,'release/phase2-test-report.json'),selection=validateBuildSelection(JSON.parse(readFileSync(selectionPath,'utf8'))),testReport=validatePhase2TestReport(JSON.parse(readFileSync(testReportPath,'utf8')),selection),receipt=validatePhase2ArtifactReceipt(JSON.parse(readFileSync(resolve(receiptPath),'utf8')),{selection,testReport}),prompt=readFileSync(resolve(promptPath),'utf8');validatePhase2InstallPrompt(prompt,receipt);
    const head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),selectedTree=execFileSync('git',['rev-parse',`${selection.commit}^{tree}`],{cwd:root,encoding:'utf8'}).trim(),sourcePaths=['apps','packages','scripts','tests','package.json','package-lock.json','tsconfig.json','playwright.config.ts','vitest.config.ts'];
    try{execFileSync('git',['merge-base','--is-ancestor',selection.commit,head],{cwd:root,stdio:'ignore'});execFileSync('git',['diff','--quiet',selection.commit,'--',...sourcePaths],{cwd:root,stdio:'ignore'});}catch{reject('PHASE2_SOURCE_DRIFT');}if(selectedTree!==selection.tree||hashBuildInputs(root)!==selection.sourceSha256)reject('PHASE2_SOURCE_DRIFT');
    for(const target of Object.values(receipt.targets)){const bytes=readFileSync(join(root,target.localPath));if(bytes.length!==target.bytes||digest(bytes)!==target.sha256)reject('PHASE2_ARTIFACTS_INVALID');}
    const license=JSON.parse(readFileSync(join(root,'package.json'),'utf8')).license;if(license!==receipt.license||!readFileSync(join(root,'LICENSE'),'utf8').includes('PolyForm Noncommercial License 1.0.0'))reject('LICENSE_MISMATCH');
    return Object.freeze({status:'pass',version:receipt.version,tag:receipt.tag,buildId:receipt.buildId,selectionSha256:receipt.selectionSha256,testReportSha256:receipt.testReportSha256,manifestSha256:receipt.manifestSha256,promptSha256:receipt.promptSha256,capabilitiesSha256:receipt.capabilitiesSha256,targets:Object.keys(receipt.targets),history:scanReachableHistory(root,selection.commit)});
  }catch(error){if(error instanceof Error&&['PHASE2_SOURCE_DRIFT','PHASE2_ARTIFACTS_INVALID','PHASE2_PROMPT_INVALID','LICENSE_MISMATCH','SOURCE_HISTORY_REJECTED'].includes(error.message))throw error;reject('PHASE2_ARTIFACTS_INVALID');}
}

export function phase2IdentityOnly({root=repo}={}){
  try{
    const trust=JSON.parse(readFileSync(join(root,'release/trust-root.json'),'utf8')),license=JSON.parse(readFileSync(join(root,'package.json'),'utf8')).license,isolated=process.platform==='darwin'?join(homedir(),'Library/Application Support/AutoED-Rebuild-Release/github'):join(process.env.LOCALAPPDATA??'','AutoED-Rebuild-Release/github'),env={...process.env,GH_CONFIG_DIR:isolated},run=(file,args,options={})=>execFileSync(file,args,{cwd:root,encoding:'utf8',timeout:30000,maxBuffer:2*1024*1024,...options}).trim();
    if(trust.fingerprint!==phase2Fingerprint||license!=='PolyForm-Noncommercial-1.0.0'||(lstatSync(dirname(isolated)).mode&0o777)!==0o700||(lstatSync(isolated).mode&0o777)!==0o700)reject('RELEASE_IDENTITY_MISMATCH');
    const localName=run('git',['config','--local','user.name']),localEmail=run('git',['config','--local','user.email']),isolatedLogin=run('gh',['api','user','--jq','.login'],{env}),repository=JSON.parse(run('gh',['api','repos/returdex/AutoED'],{env})),remotes=run('git',['remote']).split('\n').filter(Boolean);
    if(localName!=='returdex'||!approvedEmail(localEmail)||isolatedLogin!=='returdex'||repository.full_name!=='returdex/AutoED'||repository.owner?.login!=='returdex'||repository.id!==1350421724||repository.private!==false||remotes.join(',')!=='origin'||run('git',['remote','get-url','origin'])!=='https://github.com/returdex/AutoED.git')reject('RELEASE_IDENTITY_MISMATCH');
    return Object.freeze({status:'pass',owner:'returdex',repository:'returdex/AutoED',repositoryId:1350421724,fingerprint:phase2Fingerprint,license,remote:'origin',immutable:true});
  }catch(error){if(error instanceof Error&&error.message==='RELEASE_IDENTITY_MISMATCH')throw error;reject('RELEASE_IDENTITY_MISMATCH');}
}

if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const args=process.argv.slice(2);let result;if(args.join(' ')==='--identity-only')result=identityOnly();else if(args[0]==='--artifacts'&&args.length===2)result=artifactPreflight(args[1]);else if(args.length===5&&args[0]==='--phase2'&&args[2]==='--prompt'&&args[4]==='--read-only')result=phase2ArtifactPreflight(args[1],args[3]);else reject('RELEASE_ARGUMENT_INVALID');process.stdout.write(JSON.stringify(result)+'\n');}catch(error){const allowed=new Set(['RELEASE_ARGUMENT_INVALID','RELEASE_PREREQUISITES_INVALID','RELEASE_IDENTITY_MISMATCH','REPOSITORY_CONFLICT','RELEASE_ARTIFACTS_INVALID','PHASE2_ARTIFACTS_INVALID','PHASE2_PROMPT_INVALID','PHASE2_SOURCE_DRIFT','LICENSE_MISMATCH','SOURCE_HISTORY_REJECTED']);process.stderr.write((allowed.has(error?.message)?error.message:'RELEASE_PREFLIGHT_FAILED')+'\n');process.exitCode=1;}}
