import {execFileSync} from 'node:child_process';
import {closeSync,existsSync,fsyncSync,linkSync,lstatSync,openSync,readFileSync,realpathSync,unlinkSync,writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {homedir} from 'node:os';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {artifactPreflight,identityOnly,phase2ArtifactPreflight,phase2IdentityOnly} from './preflight.mjs';
import {phase2VersionSetSha256} from './phase2-gate.mjs';
export function createPublishPlan({preflight,approvalReceipt,version,assets}){
  if(preflight?.status!=='pass'||approvalReceipt?.schema!==1||approvalReceipt?.plan!=='01-13'||approvalReceipt?.status!=='approved'||approvalReceipt?.repository!=='returdex/AutoED'||approvalReceipt?.version!==version)throw new Error('PUBLISH_APPROVAL_REQUIRED');
  if(!Array.isArray(assets)||!assets.length||new Set(assets.map(x=>x.name)).size!==assets.length)throw new Error('PUBLISH_ASSETS_INVALID');
  return Object.freeze({status:'planned',repository:'returdex/AutoED',version,immutable:true,assets:assets.map(x=>Object.freeze({name:x.name,sha256:x.sha256,bytes:x.bytes}))});
}

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),publicationPath=join(root,'release/publication.json');
function atomic(value){writeFileSync(publicationPath+'.tmp',JSON.stringify(value,null,2)+'\n',{mode:0o600});execFileSync('/bin/mv',[publicationPath+'.tmp',publicationPath]);}
export function publishPair(path){
  const pairPath=resolve(path),pair=JSON.parse(readFileSync(pairPath,'utf8')),preflight=artifactPreflight(pairPath),isolated=process.platform==='darwin'?join(homedir(),'Library/Application Support/AutoED-Rebuild-Release/github'):join(process.env.LOCALAPPDATA??'','AutoED-Rebuild-Release/github'),env={...process.env,GH_CONFIG_DIR:isolated},run=(file,args,extra={})=>(execFileSync(file,args,{cwd:root,env,encoding:'utf8',timeout:extra.timeout??300000,maxBuffer:16*1024*1024,stdio:extra.stdio??['ignore','pipe','pipe']})??'').trim();
  let receipt=existsSync(publicationPath)?JSON.parse(readFileSync(publicationPath,'utf8')):null;if(!receipt){identityOnly();let canonical='';try{canonical=run('gh',['api','repos/returdex/AutoED','--jq','.full_name']);}catch{}if(canonical==='returdex/AutoED')throw new Error('REPOSITORY_CONFLICT');const created=JSON.parse(run('gh',['api','--method','POST','user/repos','-f','name=AutoED','-f','description=Local course information sync and archive service','-F','private=false']));if(created.full_name!=='returdex/AutoED'||created.private!==false||!Number.isSafeInteger(created.id))throw new Error('REPOSITORY_CREATION_FAILED');receipt={schema:1,plan:'01-13',status:'repository_created',repository:'returdex/AutoED',repositoryId:created.id,visibility:'public',createdAt:new Date().toISOString(),sourceHead:preflight.head,releases:[]};atomic(receipt);}
  if(receipt.repository!=='returdex/AutoED'||receipt.visibility!=='public'||!Number.isSafeInteger(receipt.repositoryId))throw new Error('PUBLICATION_RECEIPT_INVALID');const remotes=run('git',['remote']).split('\n').filter(Boolean);if(!remotes.length)run('git',['remote','add','origin','https://github.com/returdex/AutoED.git']);else if(remotes.join(',')!=='origin'||run('git',['remote','get-url','origin'])!=='https://github.com/returdex/AutoED.git')throw new Error('REMOTE_CONFLICT');
  for(const release of pair.versions){const localTags=run('git',['tag','--list',release.version]);if(!localTags)run('git',['tag','-a',release.version,release.commit,'-m',`AutoED ${release.version} synthetic beta`]);else if(run('git',['rev-list','-n','1',release.version])!==release.commit)throw new Error('VERSION_ALREADY_EXISTS');}
  const helper='!gh auth git-credential';run('git',['-c','credential.helper=','-c',`credential.helper=${helper}`,'push','-u','origin','main'],{timeout:300000,stdio:'inherit'});run('git',['-c','credential.helper=','-c',`credential.helper=${helper}`,'push','origin',...pair.versions.map(v=>v.version)],{timeout:300000,stdio:'inherit'});
  for(const release of pair.versions){if(receipt.releases.some(x=>x.version===release.version))continue;let existing='';try{existing=run('gh',['release','view',release.version,'--repo','returdex/AutoED','--json','tagName','--jq','.tagName']);}catch{}if(existing)throw new Error('VERSION_ALREADY_EXISTS');const assets=[...release.targets.flatMap(t=>t.assets),...release.shared],paths=assets.map(a=>join(root,a.localPath));run('gh',['release','create',release.version,...paths,'--repo','returdex/AutoED','--title',`AutoED ${release.version}`,'--notes',`Synthetic beta for manual installation and upgrade UAT. Windows native and human UAT remain not_run. Trust fingerprint: ${pair.fingerprint}`,'--prerelease','--verify-tag'],{timeout:3600000,stdio:'inherit'});receipt.releases.push({version:release.version,tagCommit:release.commit,assets:assets.map(a=>a.name),publishedAt:new Date().toISOString()});receipt.status=pair.versions.every(candidate=>receipt.releases.some(item=>item.version===candidate.version))?'published':'publishing';atomic(receipt);}
  return Object.freeze({status:receipt.status,repository:receipt.repository,repositoryId:receipt.repositoryId,releases:receipt.releases.map(x=>({version:x.version,assets:x.assets.length}))});
}

const PHASE2_VERSION=/^0\.1\.0-beta\.([1-9]\d*)$/;
const PHASE2_HASH=/^[a-f0-9]{64}$/;
const PHASE2_GIT=/^[a-f0-9]{40}$/;
function phase2Fail(code){throw new Error(code);}
function phase2Exact(value,keys){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join(',')===[...keys].sort().join(',');}
export function isAbsentPhase2CommitLookup(error,tag){if(typeof tag!=='string'||!/^v0\.1\.0-beta\.[1-9]\d*$/.test(tag))return false;const escaped=tag.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),stderr=String(error?.stderr??'').trim();return new RegExp(`^(?:gh:\\s*)?No commit found for SHA: ${escaped} \\(HTTP 422\\)$`).test(stderr);}
function phase2ConsumedBefore(version){const selected=Number(PHASE2_VERSION.exec(version)?.[1]);if(!Number.isSafeInteger(selected)||selected<1)phase2Fail('PHASE2_PUBLICATION_RELEASE_INVALID');return Array.from({length:selected-1},(_,index)=>`0.1.0-beta.${index+1}`);}
function phase2Asset(value,target){return phase2Exact(value,['id','name','bytes','sha256','url'])&&Number.isSafeInteger(value.id)&&value.id>0&&value.name===target.name&&value.bytes===target.bytes&&value.sha256===target.sha256&&value.url===target.url;}
function phase2Remote(value,release,before){
  if(!phase2Exact(value,['schema','owner','repositoryId','versions','versionSetSha256','tag','release','assets',...(before?[]:['metadata'])])||value.schema!==1||value.owner!=='returdex'||value.repositoryId!==1350421724||!Array.isArray(value.versions)||new Set(value.versions).size!==value.versions.length||value.versions.some(version=>!PHASE2_VERSION.test(version))||!PHASE2_HASH.test(value.versionSetSha256)||(before?!Array.isArray(value.assets):!phase2Exact(value.assets,['macos','windows'])))phase2Fail('PHASE2_PUBLICATION_REMOTE_INVALID');
  const selected=Number(PHASE2_VERSION.exec(release.version)?.[1]),numbers=value.versions.map(version=>Number(PHASE2_VERSION.exec(version)?.[1])),sorted=[...value.versions].sort((a,b)=>Number(PHASE2_VERSION.exec(a)[1])-Number(PHASE2_VERSION.exec(b)[1])),consumed=phase2ConsumedBefore(release.version);
  if(JSON.stringify(value.versions)!==JSON.stringify(sorted)||value.versionSetSha256!==phase2VersionSetSha256(value.versions)||release.versionSetSha256!==phase2VersionSetSha256(consumed))phase2Fail('PHASE2_PUBLICATION_VERSION_CONFLICT');
  if(before){if(numbers.some(number=>number>=selected)||value.tag!==null||value.release!==null||value.assets.length!==0)phase2Fail('PHASE2_PUBLICATION_VERSION_CONFLICT');return value;}
  if(!value.versions.includes(release.version)||!phase2Exact(value.tag,['name','commit','immutable'])||value.tag.name!==release.tag||value.tag.commit!==release.commit||value.tag.immutable!==true||!phase2Exact(value.release,['version','tag','buildId','immutable'])||value.release.version!==release.version||value.release.tag!==release.tag||value.release.buildId!==release.buildId||value.release.immutable!==true||!phase2Exact(value.assets,['macos','windows'])||!phase2Asset(value.assets.macos,release.targets.macos)||!phase2Asset(value.assets.windows,release.targets.windows)||!phase2Exact(value.metadata,['manifestSha256','installPromptCoreSha256','externalPromptSha256','capabilitiesSha256'])||value.metadata.manifestSha256!==release.manifestSha256||value.metadata.installPromptCoreSha256!==release.installPromptCoreSha256||value.metadata.externalPromptSha256!==release.externalPromptSha256||value.metadata.capabilitiesSha256!==release.capabilitiesSha256)phase2Fail('PHASE2_PUBLICATION_CONFIRMATION_INVALID');return value;
}
function phase2Release(value){const keys=['schema','status','owner','repository','repositoryId','version','tag','commit','tree','buildId','selectionSha256','testReportSha256','sourceSha256','versionSetSha256','manifestSha256','fingerprint','license','immutable','installPromptCoreSha256','externalPromptSha256','capabilitiesSha256','targets','gaps'],targetKeys=['name','localPath','url','bytes','sha256','manifestSha256','signatureSha256','capabilityClosureSha256'];if(!phase2Exact(value,keys)||value.schema!==1||value.status!=='built_signed_verified_local'||value.owner!=='returdex'||value.repository!=='returdex/AutoED'||value.repositoryId!==1350421724||!PHASE2_VERSION.test(value.version)||value.tag!==`v${value.version}`||!PHASE2_GIT.test(value.commit)||!PHASE2_GIT.test(value.tree)||!PHASE2_HASH.test(value.buildId)||!PHASE2_HASH.test(value.selectionSha256)||!PHASE2_HASH.test(value.testReportSha256)||!PHASE2_HASH.test(value.sourceSha256)||!PHASE2_HASH.test(value.versionSetSha256)||value.versionSetSha256!==phase2VersionSetSha256(phase2ConsumedBefore(value.version))||!PHASE2_HASH.test(value.manifestSha256)||!PHASE2_HASH.test(value.installPromptCoreSha256)||!PHASE2_HASH.test(value.externalPromptSha256)||!PHASE2_HASH.test(value.capabilitiesSha256)||value.fingerprint!=='fe7168c33489a34aaac2cefba36bc62bca76f9406a4b7293927a6b7e22201557'||value.license!=='PolyForm-Noncommercial-1.0.0'||value.immutable!==true||!phase2Exact(value.targets,['macos','windows'])||!phase2Exact(value.gaps,['windowsNative','live','phase3'])||value.gaps.windowsNative!=='not_run/human_needed'||value.gaps.live!=='not_run/human_needed'||value.gaps.phase3!=='blocked')phase2Fail('PHASE2_PUBLICATION_RELEASE_INVALID');for(const [platform,target]of Object.entries(value.targets)){if(!phase2Exact(target,targetKeys)||!target.name.includes(platform==='macos'?'darwin-arm64':'win32-x64')||target.localPath!==`.runtime/releases/${value.version}/${target.name}`||target.url!==`https://github.com/returdex/AutoED/releases/download/${value.tag}/${encodeURIComponent(target.name)}`||!Number.isSafeInteger(target.bytes)||target.bytes<1||target.bytes>2*1024*1024*1024||['sha256','manifestSha256','signatureSha256','capabilityClosureSha256'].some(key=>!PHASE2_HASH.test(target[key])))phase2Fail('PHASE2_PUBLICATION_RELEASE_INVALID');}return value;}
function phase2PreflightMatches(value,release){return value?.status==='pass'&&value.version===release.version&&value.tag===release.tag&&value.buildId===release.buildId&&value.selectionSha256===release.selectionSha256&&value.testReportSha256===release.testReportSha256&&value.manifestSha256===release.manifestSha256&&value.installPromptCoreSha256===release.installPromptCoreSha256&&value.externalPromptSha256===release.externalPromptSha256&&value.capabilitiesSha256===release.capabilitiesSha256&&Array.isArray(value.targets)&&value.targets.length===2&&value.targets[0]==='macos'&&value.targets[1]==='windows';}
function phase2Receipt(release,remote,checkedAt){return Object.freeze({schema:1,status:'pass',owner:'returdex',repositoryId:1350421724,version:release.version,tag:release.tag,buildId:release.buildId,manifestSha256:release.manifestSha256,immutable:true,assets:remote.assets,checkedAt});}
function writeNoReplace(path,value,allowedRoot){try{const outputRoot=realpathSync(allowedRoot),target=resolve(path),repositoryRelease=realpathSync(join(root,'release'));if(dirname(target)!==outputRoot||existsSync(target)||!lstatSync(outputRoot).isDirectory()||lstatSync(outputRoot).isSymbolicLink()||(outputRoot!==repositoryRelease&&(lstatSync(outputRoot).mode&0o077)!==0))phase2Fail('PHASE2_PUBLICATION_RECEIPT_INVALID');const temporary=join(outputRoot,`.phase2-publication-${randomUUID()}`);let fd;try{fd=openSync(temporary,'wx',0o600);writeFileSync(fd,JSON.stringify(value,null,2)+'\n');fsyncSync(fd);closeSync(fd);fd=undefined;linkSync(temporary,target);unlinkSync(temporary);if(process.platform==='darwin'){const directory=openSync(outputRoot,'r');try{fsyncSync(directory);}finally{closeSync(directory);}}}catch(error){if(fd!==undefined)try{closeSync(fd);}catch{}try{if(existsSync(temporary))unlinkSync(temporary);}catch{}throw error;}}catch(error){if(error instanceof Error&&error.message==='PHASE2_PUBLICATION_RECEIPT_INVALID')throw error;if(error?.code==='EEXIST')phase2Fail('PHASE2_PUBLICATION_RECEIPT_EXISTS');phase2Fail('PHASE2_PUBLICATION_RECEIPT_INVALID');}}
export async function publishPhase2Release({release:releaseInput,receiptPath,deps}){
  const release=phase2Release(releaseInput);if(!deps||typeof deps.preflight!=='function'||typeof deps.observeRemote!=='function'||typeof deps.publish!=='function'||typeof deps.now!=='function')phase2Fail('PHASE2_PUBLICATION_RUNTIME_INVALID');if(existsSync(receiptPath))phase2Fail('PHASE2_PUBLICATION_RECEIPT_EXISTS');const preflight=await deps.preflight();if(!phase2PreflightMatches(preflight,release))phase2Fail('PHASE2_PUBLICATION_PREFLIGHT_FAILED');const before=phase2Remote(await deps.observeRemote(),release,true);await deps.publish(Object.freeze({repository:'returdex/AutoED',repositoryId:1350421724,version:release.version,tag:release.tag,commit:release.commit,immutable:true,assets:Object.values(release.targets).map(target=>({name:target.name,localPath:target.localPath,bytes:target.bytes,sha256:target.sha256})),metadata:{manifestSha256:release.manifestSha256,installPromptCoreSha256:release.installPromptCoreSha256,externalPromptSha256:release.externalPromptSha256,capabilitiesSha256:release.capabilitiesSha256},before}));const after=phase2Remote(await deps.observeRemote(),release,false),expectedVersions=[...before.versions,release.version].sort((a,b)=>Number(PHASE2_VERSION.exec(a)[1])-Number(PHASE2_VERSION.exec(b)[1]));if(JSON.stringify(after.versions)!==JSON.stringify(expectedVersions))phase2Fail('PHASE2_PUBLICATION_VERSION_CONFLICT');const checkedAt=new Date(deps.now()).toISOString(),receipt=phase2Receipt(release,after,checkedAt);writeNoReplace(receiptPath,receipt,deps.receiptRoot??dirname(receiptPath));return receipt;
}

function phase2ProductionDependencies(releasePath,release){
  const isolated=process.platform==='darwin'?join(homedir(),'Library/Application Support/AutoED-Rebuild-Release/github'):join(process.env.LOCALAPPDATA??'','AutoED-Rebuild-Release/github'),env={...process.env,GH_CONFIG_DIR:isolated},run=(file,args,options={})=>(execFileSync(file,args,{cwd:root,env,encoding:'utf8',timeout:options.timeout??300000,maxBuffer:8*1024*1024,stdio:['ignore','pipe','pipe']})??'').trim(),optional=(args,missingCommitTag=null)=>{try{return run('gh',args);}catch(error){const message=String(error?.stderr??'');if(/(?:HTTP 404|Not Found)/i.test(message)||missingCommitTag!==null&&isAbsentPhase2CommitLookup(error,missingCommitTag))return null;throw error;}};
  const releaseApi=()=>{const raw=optional(['api',`repos/returdex/AutoED/releases/tags/${release.tag}`]);return raw===null?null:JSON.parse(raw);};
  const observeRemote=async()=>{
    const tags=run('gh',['api','repos/returdex/AutoED/releases','--paginate','--jq','.[].tag_name']).split('\n').filter(Boolean),versions=tags.map(tag=>tag.startsWith('v')?tag.slice(1):tag).filter(version=>PHASE2_VERSION.test(version)).sort((a,b)=>Number(PHASE2_VERSION.exec(a)[1])-Number(PHASE2_VERSION.exec(b)[1])),remoteRelease=releaseApi(),commitRaw=optional(['api',`repos/returdex/AutoED/commits/${release.tag}`,'--jq','.sha'],release.tag),parsed=remoteRelease?.body?JSON.parse(remoteRelease.body):null,body=phase2Exact(parsed,['schema','owner','repositoryId','version','tag','buildId','manifestSha256','installPromptCoreSha256','externalPromptSha256','capabilitiesSha256','immutable','assets'])&&phase2Exact(parsed.assets,['macos','windows'])?parsed:null,apiAssets=remoteRelease?.assets??[],tag=commitRaw?{name:release.tag,commit:commitRaw,immutable:true}:null;
    if(!remoteRelease)return{schema:1,owner:'returdex',repositoryId:1350421724,versions,versionSetSha256:phase2VersionSetSha256(versions),tag,release:null,assets:[]};
    const publishedAssets=Object.fromEntries(['macos','windows'].map(platform=>{const declared=body?.assets?.[platform],asset=apiAssets.find(item=>item.name===declared?.name);return[platform,asset&&declared?{id:asset.id,name:asset.name,bytes:asset.size,sha256:declared.sha256,url:asset.browser_download_url}:null];}));
    return{schema:1,owner:'returdex',repositoryId:1350421724,versions,versionSetSha256:phase2VersionSetSha256(versions),tag,release:body?{version:body.version,tag:body.tag,buildId:body.buildId,immutable:body.immutable}:null,assets:apiAssets.length===2?publishedAssets:{...publishedAssets,unexpected:null},metadata:body?{manifestSha256:body.manifestSha256,installPromptCoreSha256:body.installPromptCoreSha256,externalPromptSha256:body.externalPromptSha256,capabilitiesSha256:body.capabilitiesSha256}:null};
  };
  return{receiptRoot:join(root,'release'),now:Date.now,preflight:async()=>{phase2IdentityOnly({root});return phase2ArtifactPreflight(releasePath,join(root,'release/phase2-install-prompt.md'),{root});},observeRemote,publish:async plan=>{
    const helper='!gh auth git-credential';run('git',['-c','credential.helper=','-c',`credential.helper=${helper}`,'push','origin',`${plan.commit}:refs/heads/main`],{timeout:600000});
    const preliminary={schema:1,owner:'returdex',repositoryId:1350421724,version:release.version,tag:release.tag,buildId:release.buildId,manifestSha256:release.manifestSha256,installPromptCoreSha256:release.installPromptCoreSha256,externalPromptSha256:release.externalPromptSha256,capabilitiesSha256:release.capabilitiesSha256,immutable:true,assets:Object.fromEntries(Object.entries(release.targets).map(([platform,target])=>[platform,{id:0,name:target.name,bytes:target.bytes,sha256:target.sha256,url:target.url}]))};
    run('gh',['release','create',release.tag,...plan.assets.map(asset=>join(root,asset.localPath)),'--repo','returdex/AutoED','--target',release.commit,'--title',`AutoED ${release.version}`,'--notes',JSON.stringify(preliminary),'--prerelease'],{timeout:3600000});
    const created=releaseApi();if(!created||created.tag_name!==release.tag||created.target_commitish!==release.commit||created.assets?.length!==2)phase2Fail('PHASE2_PUBLICATION_CONFIRMATION_INVALID');const assets=Object.fromEntries(Object.entries(release.targets).map(([platform,target])=>{const item=created.assets.find(asset=>asset.name===target.name);if(!item||item.size!==target.bytes||item.browser_download_url!==target.url)phase2Fail('PHASE2_PUBLICATION_CONFIRMATION_INVALID');return[platform,{id:item.id,name:item.name,bytes:item.size,sha256:target.sha256,url:item.browser_download_url}];})),metadata={...preliminary,assets};run('gh',['release','edit',release.tag,'--repo','returdex/AutoED','--notes',JSON.stringify(metadata)]);return metadata;
  }};
}

if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const args=process.argv.slice(2);if(args[0]==='--pair'&&args.length===2)process.stdout.write(JSON.stringify(publishPair(args[1]))+'\n');else if(args.length===4&&args[0]==='--release'&&args[2]==='--receipt'){const releasePath=resolve(args[1]),receiptPath=resolve(args[3]);if(releasePath!==join(root,'release/phase2-beta-artifacts.json')||receiptPath!==join(root,'release/phase2-publication.json'))throw new Error('RELEASE_ARGUMENT_INVALID');const release=JSON.parse(readFileSync(releasePath,'utf8')),result=await publishPhase2Release({release,receiptPath,deps:phase2ProductionDependencies(releasePath,release)});process.stdout.write(JSON.stringify({status:result.status,version:result.version,tag:result.tag,assets:Object.keys(result.assets)})+'\n');}else throw new Error('RELEASE_ARGUMENT_INVALID');}catch(error){process.stderr.write((/^PHASE2_[A-Z0-9_]+$/.test(error?.message??'')||error?.message==='RELEASE_ARGUMENT_INVALID'?error.message:'PUBLISH_FAILED')+'\n');process.exitCode=1;}}
