import {execFileSync} from 'node:child_process';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {homedir} from 'node:os';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {artifactPreflight,identityOnly} from './preflight.mjs';
export function createPublishPlan({preflight,approvalReceipt,version,assets}){
  if(preflight?.status!=='pass'||approvalReceipt?.schema!==1||approvalReceipt?.plan!=='01-13'||approvalReceipt?.status!=='approved'||approvalReceipt?.repository!=='returdex/AutoED'||approvalReceipt?.version!==version)throw new Error('PUBLISH_APPROVAL_REQUIRED');
  if(!Array.isArray(assets)||!assets.length||new Set(assets.map(x=>x.name)).size!==assets.length)throw new Error('PUBLISH_ASSETS_INVALID');
  return Object.freeze({status:'planned',repository:'returdex/AutoED',version,immutable:true,assets:assets.map(x=>Object.freeze({name:x.name,sha256:x.sha256,bytes:x.bytes}))});
}

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),publicationPath=join(root,'release/publication.json');
function atomic(value){writeFileSync(publicationPath+'.tmp',JSON.stringify(value,null,2)+'\n',{mode:0o600});execFileSync('/bin/mv',[publicationPath+'.tmp',publicationPath]);}
export function publishPair(path){
  const pairPath=resolve(path),pair=JSON.parse(readFileSync(pairPath,'utf8')),preflight=artifactPreflight(pairPath),isolated=process.platform==='darwin'?join(homedir(),'Library/Application Support/AutoED-Rebuild-Release/github'):join(process.env.LOCALAPPDATA??'','AutoED-Rebuild-Release/github'),env={...process.env,GH_CONFIG_DIR:isolated},run=(file,args,extra={})=>(execFileSync(file,args,{cwd:root,env,encoding:'utf8',timeout:extra.timeout??300000,maxBuffer:16*1024*1024,stdio:extra.stdio??['ignore','pipe','pipe']})??'').trim();
  let receipt=existsSync(publicationPath)?JSON.parse(readFileSync(publicationPath,'utf8')):null;if(!receipt){identityOnly();let canonical='';try{canonical=run('gh',['api','repos/returdex/AutoED','--jq','.full_name']);}catch{}if(canonical==='returdex/AutoED')throw new Error('REPOSITORY_CONFLICT');const created=JSON.parse(run('gh',['api','--method','POST','user/repos','-f','name=AutoED','-f','description=Local course information sync and archive service','-F','private=false']));if(created.full_name!=='returdex/AutoED'||created.private!==false||!Number.isSafeInteger(created.id))throw new Error('REPOSITORY_CREATION_FAILED');receipt={schema:1,plan:'01-13',status:'repository_created',repository:'returdex/AutoED',repositoryId:created.id,visibility:'public',createdAt:new Date().toISOString(),sourceHead:preflight.head,releases:[]};atomic(receipt);}
  if(receipt.repository!=='returdex/AutoED'||receipt.visibility!=='public'||!Number.isSafeInteger(receipt.repositoryId))throw new Error('PUBLICATION_RECEIPT_INVALID');const remotes=run('git',['remote']).split('\n').filter(Boolean);if(!remotes.length)run('git',['remote','add','origin','https://github.com/returdex/AutoED.git']);else if(remotes.join(',')!=='origin'||run('git',['remote','get-url','origin'])!=='https://github.com/returdex/AutoED.git')throw new Error('REMOTE_CONFLICT');
  for(const release of pair.versions){const localTags=run('git',['tag','--list',release.version]);if(!localTags)run('git',['tag','-a',release.version,release.commit,'-m',`AutoED ${release.version} synthetic beta`]);else if(run('git',['rev-list','-n','1',release.version])!==release.commit)throw new Error('VERSION_ALREADY_EXISTS');}
  const helper='!gh auth git-credential';run('git',['-c','credential.helper=','-c',`credential.helper=${helper}`,'push','-u','origin','main'],{timeout:300000,stdio:'inherit'});run('git',['-c','credential.helper=','-c',`credential.helper=${helper}`,'push','origin',...pair.versions.map(v=>v.version)],{timeout:300000,stdio:'inherit'});
  for(const release of pair.versions){if(receipt.releases.some(x=>x.version===release.version))continue;let existing='';try{existing=run('gh',['release','view',release.version,'--repo','returdex/AutoED','--json','tagName','--jq','.tagName']);}catch{}if(existing)throw new Error('VERSION_ALREADY_EXISTS');const assets=[...release.targets.flatMap(t=>t.assets),...release.shared],paths=assets.map(a=>join(root,a.localPath));run('gh',['release','create',release.version,...paths,'--repo','returdex/AutoED','--title',`AutoED ${release.version}`,'--notes',`Synthetic beta for manual installation and upgrade UAT. Windows native and human UAT remain not_run. Trust fingerprint: ${pair.fingerprint}`,'--prerelease','--verify-tag'],{timeout:3600000,stdio:'inherit'});receipt.releases.push({version:release.version,tagCommit:release.commit,assets:assets.map(a=>a.name),publishedAt:new Date().toISOString()});receipt.status=receipt.releases.length===2?'published':'publishing';atomic(receipt);}
  return Object.freeze({status:receipt.status,repository:receipt.repository,repositoryId:receipt.repositoryId,releases:receipt.releases.map(x=>({version:x.version,assets:x.assets.length}))});
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const args=process.argv.slice(2);if(args[0]!=='--pair'||args.length!==2)throw new Error('RELEASE_ARGUMENT_INVALID');process.stdout.write(JSON.stringify(publishPair(args[1]))+'\n');}catch(error){process.stderr.write((error?.message??'PUBLISH_FAILED')+'\n');process.exitCode=1;}}
