import {createHash,randomUUID} from 'node:crypto';
import {existsSync,readFileSync,lstatSync,writeFileSync,openSync,closeSync,fsyncSync,linkSync,unlinkSync,mkdirSync,chmodSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {z} from 'zod';
import {BuildIdentitySchema} from '../../contracts/src/index.js';
import {readInstallation} from '../../platform/src/installation.js';
import {assertManagedPath,managedPaths,type RootSelection} from '../../platform/src/paths.js';
import {protectPath,windowsProbe} from '../../platform/src/permissions.js';
import {isVerifiedManifest,verifyFileTree,type VerifiedManifest} from './verify-manifest.js';
import type {InstallPreview} from './preview.js';
const sha=(bytes:string|Buffer)=>createHash('sha256').update(bytes).digest('hex'),hash=z.string().regex(/^[a-f0-9]{64}$/);
const ActiveSchema=z.strictObject({schema:z.literal(1),installationId:z.uuid(),scopeHash:hash,manifestHash:hash,build:BuildIdentitySchema,nodeVersion:z.literal('24.20.0'),browserRevision:z.literal('1234'),nodeSha256:hash,cliSha256:hash,mcpSha256:hash,state:z.literal('staged')});
export type ActiveRecord=z.infer<typeof ActiveSchema>;
export function programEntryPaths(manifest:VerifiedManifest){
  const program=manifest.manifest.artifacts.find(a=>a.role==='program');if(!program)throw new Error('ENTRY_MISSING');
  const required=['apps/cli/src/main.js','apps/mcp/src/main.js'] as const;
  const layouts=['','dist/'].map(prefix=>({prefix,files:Object.fromEntries(required.map(path=>[path,program.files.find(file=>file.path===prefix+path&&file.type!=='symlink')]))})).filter(layout=>required.every(path=>layout.files[path]));
  if(layouts.length!==1)throw new Error('ENTRY_MISSING');const layout=layouts[0]!;
  return {program,prefix:layout.prefix,api:layout.prefix+'apps/api/src/main.js',worker:layout.prefix+'apps/worker/src/main.js',cli:layout.prefix+required[0],mcp:layout.prefix+required[1],clientHost:layout.prefix+'packages/platform/src/client-host.js',identity:layout.prefix+'build/identity.json',cliFile:layout.files[required[0]]!,mcpFile:layout.files[required[1]]!};
}
export function writeInstallerRecord(path:string,value:unknown){if(existsSync(path))throw new Error('ENTRY_OWNERSHIP_UNCONFIRMED');const temporary=join(dirname(path),'.record-'+randomUUID()),fd=openSync(temporary,'wx',0o600);try{protectPath(temporary);writeFileSync(fd,JSON.stringify(value));fsyncSync(fd);}finally{closeSync(fd);}/* Atomic no-replace publication: never rename over an unknown competing entry. */linkSync(temporary,path);unlinkSync(temporary);if(process.platform==='darwin'){const directory=openSync(dirname(path),'r');try{fsyncSync(directory);}finally{closeSync(directory);}}}
export function readActive(selection:RootSelection):ActiveRecord{
  const metadata=readInstallation(selection),path=assertManagedPath(managedPaths(selection.root),'active.json');if(lstatSync(path).size>8192)throw new Error('ACTIVE_INVALID');const active=ActiveSchema.parse(JSON.parse(readFileSync(path,'utf8')));if(active.installationId!==metadata.installationId)throw new Error('ACTIVE_INVALID');return active;
}
function quoted(value:string){return "'"+value.replaceAll("'","'\\''")+"'";}
export function publishLaunchers(preview:InstallPreview,manifest:VerifiedManifest,candidateOperationId?:string){
  if(!isVerifiedManifest(manifest)||manifest.manifestHash!==preview.manifestHash)throw new Error('VERIFIED_MANIFEST_REQUIRED');const metadata=readInstallation(preview.selection);if(metadata.installationId!==preview.installationId)throw new Error('INSTALLATION_MISMATCH');
  const entries=programEntryPaths(manifest),program=entries.program,node=manifest.manifest.artifacts.find(a=>a.role==='node')!,browser=manifest.manifest.artifacts.find(a=>a.role==='browser')!;
  for(const [artifact,root]of [[program,preview.paths.program],[node,preview.paths.runtime],[browser,preview.paths.browser]] as const)verifyFileTree(manifest,artifact.name,root);
  const nodeName=process.platform==='darwin'?'bin/node':'bin/node.exe',nodeFile=node.files.find(f=>f.path===nodeName&&f.type!=='symlink');if(!nodeFile)throw new Error('ENTRY_MISSING');
  const active=ActiveSchema.parse({schema:1,installationId:preview.installationId,scopeHash:preview.scopeHash,manifestHash:preview.manifestHash,build:preview.target,nodeVersion:'24.20.0',browserRevision:'1234',nodeSha256:nodeFile.sha256,cliSha256:entries.cliFile.sha256,mcpSha256:entries.mcpFile.sha256,state:'staged'}),activeBytes=JSON.stringify(active),nodePath=join(preview.paths.runtime,nodeName);
  const cfg={root:preview.selection.root,parent:preview.selection.parent,installationId:preview.installationId,activeHash:sha(activeBytes),program:preview.paths.program,nodePath,files:program.files,entries:{cli:entries.cli,mcp:entries.mcp}};
  const resolver=`import {readFileSync,lstatSync,realpathSync,readdirSync} from 'node:fs';
import {join} from 'node:path';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';
const cfg=${JSON.stringify(cfg)};const hash=b=>createHash('sha256').update(b).digest('hex');
try{const canonical=path=>process.platform==='win32'?realpathSync(path).toLowerCase()===path.toLowerCase():realpathSync(path)===path;const root=lstatSync(cfg.root);if(!root.isDirectory()||root.isSymbolicLink()||!canonical(cfg.root)||!canonical(cfg.program)||!canonical(cfg.nodePath))throw new Error();const record=name=>{const path=join(cfg.root,name),s=lstatSync(path);if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1||s.size>65536||!canonical(path))throw new Error();return readFileSync(path);};const bytes=record('active.json');if(hash(bytes)!==cfg.activeHash)throw new Error();const active=JSON.parse(bytes),metadata=JSON.parse(record('installation.json'));if(metadata.installationId!==cfg.installationId||active.installationId!==cfg.installationId||metadata.ownership.device!==root.dev||metadata.ownership.inode!==root.ino||metadata.ownership.uid!==root.uid||active.build.protocol!==1||active.build.schemaMin!==1||active.build.schemaMax!==1)throw new Error();
const files=new Map(cfg.files.map(f=>[f.path,f])),dirs=new Set();for(const f of cfg.files){const p=f.path.split('/');for(let i=1;i<p.length;i++)dirs.add(p.slice(0,i).join('/'));}let count=0;const walk=(dir,prefix='')=>{for(const e of readdirSync(dir,{withFileTypes:true})){const p=prefix+e.name;if(e.isDirectory()){if(!dirs.has(p))throw new Error();walk(join(dir,e.name),p+'/');}else{const f=files.get(p),path=join(dir,e.name),s=lstatSync(path);if(!f||!s.isFile()||s.isSymbolicLink()||s.nlink!==1||realpathSync(path)!==path||s.size!==f.bytes||hash(readFileSync(path))!==f.sha256)throw new Error();count++;}}};walk(cfg.program);if(count!==cfg.files.length||hash(readFileSync(cfg.nodePath))!==active.nodeSha256)throw new Error();
const args=process.argv.slice(2),role=args[0]==='mcp'?(args.shift(),'mcp'):'cli';const entry=join(cfg.program,cfg.entries[role]);process.argv=[process.execPath,entry,'--root',cfg.root,'--parent',cfg.parent,...args];await import(pathToFileURL(entry).href);
}catch{process.stderr.write('ACTIVE_INTEGRITY_FAILED\\n');process.exitCode=1;}
`;
  const outputBin=candidateOperationId?assertManagedPath(managedPaths(preview.selection.root),`installer-staging/activation-${z.uuid().parse(candidateOperationId)}/new-bin`):preview.paths.bin;
  if(existsSync(outputBin))throw new Error('ENTRY_OWNERSHIP_UNCONFIRMED');mkdirSync(outputBin,{mode:0o700});protectPath(outputBin);
  const resolverPath=join(preview.paths.bin,'launcher.mjs');const command=join(preview.paths.bin,process.platform==='darwin'?'autoed-rebuild':'autoed-rebuild.cmd');
  let launcher:string;
  if(process.platform==='darwin')launcher=`#!/bin/sh\nset -eu\n[ -f ${quoted(nodePath)} ] && [ ! -L ${quoted(nodePath)} ] && [ -f ${quoted(resolverPath)} ] && [ ! -L ${quoted(resolverPath)} ] || exit 1\n[ "$(cd ${quoted(dirname(nodePath))} && /bin/pwd -P)" = ${quoted(dirname(nodePath))} ] || exit 1\n[ "$(cd ${quoted(dirname(resolverPath))} && /bin/pwd -P)" = ${quoted(dirname(resolverPath))} ] || exit 1\n[ "$(/usr/bin/shasum -a 256 ${quoted(nodePath)} | /usr/bin/awk '{print $1}')" = '${nodeFile.sha256}' ] || exit 1\n[ "$(/usr/bin/shasum -a 256 ${quoted(resolverPath)} | /usr/bin/awk '{print $1}')" = '${sha(resolver)}' ] || exit 1\nexec /usr/bin/env -i PATH=/usr/bin:/bin ${quoted(nodePath)} ${quoted(resolverPath)} "$@"\n`;
  else {const guard=`$ErrorActionPreference='Stop';$bin=$env:AUTOED_REBUILD_BIN;$node=Join-Path $bin '..\\runtime\\24.20.0\\bin\\node.exe';$resolver=Join-Path $bin 'launcher.mjs';if((Get-FileHash -LiteralPath $node -Algorithm SHA256).Hash.ToLowerInvariant() -ne '${nodeFile.sha256}' -or (Get-FileHash -LiteralPath $resolver -Algorithm SHA256).Hash.ToLowerInvariant() -ne '${sha(resolver)}'){exit 1}`;launcher=`@echo off\r\nsetlocal DisableDelayedExpansion\r\nset "AUTOED_REBUILD_BIN=%~dp0"\r\n"${join(process.env.SystemRoot??'C:\\Windows','System32','WindowsPowerShell','v1.0','powershell.exe')}" -NoProfile -NonInteractive -EncodedCommand ${Buffer.from(guard,'utf16le').toString('base64')}\r\nif errorlevel 1 exit /b 1\r\nset NODE_OPTIONS=\r\nset NODE_PATH=\r\nset NODE_DEBUG=\r\nset NODE_DEBUG_NATIVE=\r\nset NODE_V8_COVERAGE=\r\nset OPENSSL_CONF=\r\nset SSLKEYLOGFILE=\r\n"%~dp0..\\runtime\\24.20.0\\bin\\node.exe" "%~dp0launcher.mjs" %*\r\nexit /b %errorlevel%\r\n`;}
  for(const [path,content]of [[join(outputBin,'launcher.mjs'),resolver],[join(outputBin,process.platform==='darwin'?'autoed-rebuild':'autoed-rebuild.cmd'),launcher]]){const fd=openSync(path!,'wx',0o600);try{protectPath(path!);writeFileSync(fd,content!);fsyncSync(fd);}finally{closeSync(fd);}}
  if(process.platform==='darwin')chmodSync(join(outputBin,'autoed-rebuild'),0o700);
  writeInstallerRecord(join(outputBin,'ownership.json'),{installationId:preview.installationId,scopeHash:preview.scopeHash,files:[{name:'launcher.mjs',sha256:sha(resolver)},{name:process.platform==='darwin'?'autoed-rebuild':'autoed-rebuild.cmd',sha256:sha(launcher)}]});writeInstallerRecord(candidateOperationId?join(outputBin,'..','new-active.json'):join(preview.selection.root,'active.json'),active);return active;
}
export function assertOwnedLaunchers(selection:RootSelection){
  const active=readActive(selection),receiptPath=assertManagedPath(managedPaths(selection.root),'bin/ownership.json');if(lstatSync(receiptPath).size>4096)throw new Error('ENTRY_OWNERSHIP_UNCONFIRMED');
  const receipt=z.strictObject({installationId:z.uuid(),scopeHash:hash,files:z.array(z.strictObject({name:z.enum(['launcher.mjs','autoed-rebuild','autoed-rebuild.cmd']),sha256:hash})).length(2)}).parse(JSON.parse(readFileSync(receiptPath,'utf8')));
  if(receipt.installationId!==active.installationId||receipt.scopeHash!==active.scopeHash||new Set(receipt.files.map(f=>f.name)).size!==2)throw new Error('ENTRY_OWNERSHIP_UNCONFIRMED');for(const f of receipt.files){const path=join(selection.root,'bin',f.name),st=lstatSync(path);if(!st.isFile()||st.isSymbolicLink()||st.nlink!==1||sha(readFileSync(path))!==f.sha256)throw new Error('ENTRY_OWNERSHIP_UNCONFIRMED');}return active;
}
export function launcherRegistration(selection:RootSelection){
  const active=assertOwnedLaunchers(selection);if(process.platform==='darwin')return {name:'autoed-rebuild-m1',command:join(selection.root,'bin','autoed-rebuild'),args:['mcp'],autostart:false,hostConfiguration:'unchanged'} as const;
  const system=windowsProbe("[Environment]::GetFolderPath('System')|ConvertTo-Json -Compress",{});if(typeof system!=='string'||!system)throw new Error('SYSTEM_ROOT_UNCONFIRMED');const resolver=join(selection.root,'bin','launcher.mjs'),resolverHash=sha(readFileSync(resolver)),rootBase64=Buffer.from(selection.root).toString('base64');
  const code=`$ErrorActionPreference='Stop';try{$root=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${rootBase64}'));$node=Join-Path $root 'runtime\\24.20.0\\bin\\node.exe';$resolver=Join-Path $root 'bin\\launcher.mjs';foreach($path in @($node,$resolver)){$cursor=$path;while($cursor){$item=Get-Item -LiteralPath $cursor -Force;if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint)-ne 0){throw 'path'};$cursor=[IO.Path]::GetDirectoryName($cursor)}};if((Get-FileHash -LiteralPath $node -Algorithm SHA256).Hash.ToLowerInvariant() -ne '${active.nodeSha256}' -or (Get-FileHash -LiteralPath $resolver -Algorithm SHA256).Hash.ToLowerInvariant() -ne '${resolverHash}'){throw 'hash'};$start=New-Object Diagnostics.ProcessStartInfo;$start.FileName=$node;$start.UseShellExecute=$false;$start.Arguments='"'+$resolver+'" "mcp"';$start.EnvironmentVariables.Clear();$start.EnvironmentVariables['SystemRoot']=[Environment]::GetFolderPath('Windows');$start.EnvironmentVariables['WINDIR']=[Environment]::GetFolderPath('Windows');$start.EnvironmentVariables['PATH']=[Environment]::GetFolderPath('System');$start.EnvironmentVariables['USERPROFILE']=[Environment]::GetFolderPath('UserProfile');$start.EnvironmentVariables['LOCALAPPDATA']=[Environment]::GetFolderPath('LocalApplicationData');$start.EnvironmentVariables['TEMP']=Join-Path $root 'installer-staging';$start.EnvironmentVariables['TMP']=Join-Path $root 'installer-staging';$child=New-Object Diagnostics.Process;$child.StartInfo=$start;if(!$child.Start()){throw 'start'};$child.WaitForExit();exit $child.ExitCode}catch{[Console]::Error.WriteLine('LAUNCHER_INTEGRITY_FAILED');exit 1}`;
  return {name:'autoed-rebuild-m1',command:join(system,'WindowsPowerShell','v1.0','powershell.exe'),args:['-NoLogo','-NoProfile','-NonInteractive','-EncodedCommand',Buffer.from(code,'utf16le').toString('base64')],autostart:false,hostConfiguration:'unchanged'} as const;
}
