import Database from 'better-sqlite3';
import {copyFileSync,existsSync,lstatSync,readFileSync,renameSync,openSync,closeSync,fsyncSync,readdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {join} from 'node:path';
import {z} from 'zod';
import type {SecretStore} from '../../application/src/ports.js';
import type {RootSelection} from '../../platform/src/paths.js';
import {inspectClientHosts} from '../../platform/src/client-host.js';
import {openDatabase,readGate,SQLiteMaintenanceStore} from '../../persistence/src/database.js';
import {runSelfcheck} from '../../../scripts/install/selfcheck.mjs';
import {UpgradeJournal,nextProjectionTime} from './journal.js';
import {readActive,assertOwnedLaunchers} from './launchers.js';
import {runtimeSupervisor,verifiedInstallerClient,verifiedRuntime,recoverCandidateActivation,inspectRollbackActivation} from './upgrade.js';
import {verifySnapshot} from './snapshot.js';
import type {VerifiedManifest,VerificationTarget} from './verify-manifest.js';
import {protectPath} from '../../platform/src/permissions.js';
import {databaseDigest} from './snapshot.js';
import {cleanupManaged,cleanupRuntimeInventory} from './cleanup.js';

export class RecoveryError extends Error {constructor(readonly code:'HUMAN_RECOVERY_REQUIRED',readonly causeCode:string){super(code);}}
const Failure=z.strictObject({operationId:z.uuid(),code:z.string(),generation:z.number().int().nonnegative(),writeGeneration:z.number().int().nonnegative(),projectionWritten:z.boolean().optional(),projectionCode:z.string().optional()});
const CleanupFailure=Failure.extend({code:z.string().regex(/^CLEANUP_PENDING(?:_[A-Z_]+)?_CLEANED_INTENT$/),projectionWritten:z.literal(true),projectionCode:z.literal('AUTHENTICATED_ROUTE')});
const Admission=z.strictObject({operationId:z.uuid(),buildId:z.string().regex(/^[a-f0-9]{64}$/),mode:z.enum(['selfcheck','normal_probe','blocked'])});
const pause=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
function protectedRecord(path:string){const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||stat.size>16384)throw new Error('MAINTENANCE_RECOVERY_REQUIRED');return JSON.parse(readFileSync(path,'utf8'));}
/** Detects only the exact post-activation cleanup failure that the verified rollback engine can recover. */
export function pendingCleanupRecovery(selection:RootSelection){
  const lock=join(selection.root,'installer-staging','update.lock');if(!existsSync(lock))return null;
  try{const admission=Admission.parse(protectedRecord(join(lock,'admission.json'))),failure=CleanupFailure.parse(protectedRecord(join(selection.root,'installer-staging',`failure-${admission.operationId}.json`))),journal=UpgradeJournal.read(selection,admission.operationId),last=journal.entries.at(-1);if(failure.operationId!==admission.operationId||admission.mode!=='selfcheck'||journal.recovery||journal.header.previousInstallation!=='present'||last?.stage!=='cleaned'||last.phase!=='intent'||journal.entries.length!==19)throw new Error('MAINTENANCE_RECOVERY_REQUIRED');return admission.operationId;}catch(error){if(error instanceof Error&&error.message==='MAINTENANCE_RECOVERY_REQUIRED')throw error;throw new Error('MAINTENANCE_RECOVERY_REQUIRED');}
}
async function stopAll(selection:RootSelection,manifest:VerifiedManifest){const s=runtimeSupervisor(selection,manifest);for(const i of s.registered().reverse()){const state=await s.inspect(i);if(state==='running')await s.stop(i);else if(state!=='exited')throw new RecoveryError('HUMAN_RECOVERY_REQUIRED','PROCESS_OWNERSHIP_UNCONFIRMED');}for(const h of await inspectClientHosts(selection))if(h.state!=='exited')throw new RecoveryError('HUMAN_RECOVERY_REQUIRED','HOST_OWNERSHIP_UNCONFIRMED');}
async function probe(selection:RootSelection,manifest:VerifiedManifest,operationId:string|null,generation:number,store:SecretStore){const runtime=verifiedRuntime(selection,manifest),client=verifiedInstallerClient(selection,manifest),result=await runSelfcheck({selection,managedNode:runtime.managedNode,cliEntry:runtime.entries.cli,mcpEntry:runtime.entries.mcp,manifestPath:runtime.manifestPath,operationId,generation,installerClient:client,releaseObservation:manifest.evidence==='verified_release_manifest'?{build:manifest.manifest.build,manifestHash:manifest.manifestHash,evidence:'verified_release_manifest',checkedAt:new Date().toISOString()}:undefined});if(!result?.matched||result.featureResult!=='pass'){const code=result&&'code'in result?result.code:null,detail=typeof code==='string'&&/^[A-Z_]+$/.test(code)?`_${code}`:'';throw new RecoveryError('HUMAN_RECOVERY_REQUIRED',`ROLLBACK_SELFCHECK_FAILED${detail}`);}return client;}
async function awaitStopped(supervisor:ReturnType<typeof runtimeSupervisor>){const deadline=performance.now()+10000;while(performance.now()<deadline){const states=await Promise.all(supervisor.registered().map(i=>supervisor.inspect(i)));if(states.every(s=>s==='exited'))return;await pause(100);}throw new Error('PROCESS_STOP_UNCONFIRMED');}

/** Continues the exact durable cleaned/intent boundary instead of rolling a feature-verified target back. */
export async function resumeCleanupUpgrade(selection:RootSelection,operationId:string,options:{verify:(bytes:Buffer,signature:Buffer,target:VerificationTarget)=>VerifiedManifest;secrets:SecretStore}){
  try{
    const journal=await UpgradeJournal.recover(selection,operationId),failure=CleanupFailure.parse(protectedRecord(join(selection.root,'installer-staging',`failure-${operationId}.json`))),state=UpgradeJournal.read(selection,operationId),last=state.entries.at(-1);if(last?.stage!=='cleaned'||last.phase!=='intent'||state.entries.length!==19||failure.operationId!==operationId)throw new Error('CLEANUP_RESUME_BOUNDARY_INVALID');
    const activation=join(selection.root,'installer-staging','activation-'+operationId),active=readActive(selection),inactivePath=join(activation,'inactive.json'),oldPath=existsSync(join(activation,'old-active.json'))?join(activation,'old-active.json'):inactivePath;if(!existsSync(oldPath))throw new Error('CLEANUP_RESUME_BOUNDARY_INVALID');const oldRecord=protectedRecord(oldPath) as {manifestHash?:unknown;build?:{buildId?:unknown}},oldBuild=z.string().regex(/^[a-f0-9]{64}$/).parse(oldRecord.build?.buildId),oldHash=z.string().regex(/^[a-f0-9]{64}$/).parse(oldRecord.manifestHash);
    if(journal.header.platform.os!==process.platform||journal.header.platform.arch!==process.arch||active.manifestHash!==journal.header.manifestHash||active.build.buildId!==journal.header.target.buildId)throw new Error('PLATFORM_IDENTITY_MISMATCH');const targetSpec={...journal.header.platform,schema:1,protocol:1} as const,load=(buildId:string)=>{const root=join(selection.root,'installer-staging','manifests',buildId);return options.verify(readFileSync(join(root,'manifest.json')),readFileSync(join(root,'manifest.sig')),targetSpec);},target=load(active.build.buildId),old=load(oldBuild);if(target.manifestHash!==active.manifestHash||old.manifestHash!==oldHash)throw new Error('SIGNED_MANIFEST_MISMATCH');verifiedRuntime(selection,target);verifiedRuntime(selection,old);
    const snapshot={root:join(selection.root,'installer-staging','snapshot-'+operationId),databasePath:join(selection.root,'installer-staging','snapshot-'+operationId,'snapshot.sqlite'),operationId},record=verifySnapshot(selection,snapshot),dbPath=join(selection.root,'data','jobs.sqlite'),db=openDatabase(dbPath);try{const gate=readGate(db),write=(db.prepare('SELECT write_generation AS value FROM maintenance_generation WHERE id=1').get() as {value:number}).value;if(gate.state!=='exclusive'||gate.operationId!==operationId||gate.generation!==failure.generation||write!==failure.writeGeneration||write!==record.writeGeneration)throw new Error('ROLLBACK_FENCE_CHANGED');}finally{db.close();}
    let supervisor=runtimeSupervisor(selection,target,{operationId,generation:failure.generation}),states=await Promise.all(supervisor.registered().map(i=>supervisor.inspect(i)));if(states.some(s=>s==='unknown'))throw new Error('PROCESS_OWNERSHIP_UNCONFIRMED');if(states.every(s=>s==='exited')){await supervisor.start({installationId:journal.header.installationId,role:'api',build:target.manifest.build});await supervisor.start({installationId:journal.header.installationId,role:'worker',build:target.manifest.build});}else if(states.some(s=>s!=='running'))throw new Error('PROCESS_OWNERSHIP_UNCONFIRMED');let client=verifiedInstallerClient(selection,target);
    const cleaned=await cleanupManaged({selection,operationId,currentManifest:target,oldManifest:old});if(!cleaned.complete)throw new Error(cleaned.code);await journal.append('cleaned','done');await journal.append('reopened','intent');await client.call('/api/control/maintenance',{action:'exit',operationId,expectedGeneration:failure.generation});await awaitStopped(supervisor);await journal.clientAdmission('normal_probe',target.manifest.build.buildId);supervisor=runtimeSupervisor(selection,target);await supervisor.start({installationId:journal.header.installationId,role:'api',build:target.manifest.build});await supervisor.start({installationId:journal.header.installationId,role:'worker',build:target.manifest.build});client=verifiedInstallerClient(selection,target);await journal.append('reopened','done');await journal.append('normal_verified','intent');client=await probe(selection,target,null,failure.generation+1,options.secrets);await journal.append('normal_verified','done');await journal.append('complete','intent');const status=await client.status();if(status.api?.build?.buildId!==target.manifest.build.buildId||status.worker?.build?.buildId!==target.manifest.build.buildId||status.selfcheck?.featureResult!=='pass')throw new Error('FEATURE_SELFCHECK_FAILED');await journal.append('complete','done');const projectionDb=openDatabase(dbPath);try{const gate=readGate(projectionDb),value={operationId,stage:'complete',result:'succeeded',targetBuild:journal.header.target,actualBuild:target.manifest.build,cleanup:'complete',previousInstallation:'present',checkedAt:await nextProjectionTime(projectionDb,'install')};await client.call('/api/control/status-projection',{kind:'install',operationId:null,expectedGeneration:gate.generation,value});}finally{projectionDb.close();}await journal.release();return{state:'complete' as const,operationId,generation:failure.generation+1,build:target.manifest.build,cleanup:'complete' as const,resumed:true as const};
  }catch(error){if(error instanceof RecoveryError)throw error;throw new RecoveryError('HUMAN_RECOVERY_REQUIRED',error instanceof Error&&/^[A-Z_]+$/.test(error.message)?error.message:'CLEANUP_RESUME_FAILED');}
}

export async function recoverUpgrade(selection:RootSelection,operationId:string,options:{verify:(bytes:Buffer,signature:Buffer,target:VerificationTarget)=>VerifiedManifest;secrets:SecretStore;fault?:(stage:'restored'|'lease_renewed')=>Promise<void>}){
  try{
    const journal=await UpgradeJournal.recover(selection,operationId),failure=Failure.parse(JSON.parse(readFileSync(join(selection.root,'installer-staging',`failure-${operationId}.json`),'utf8')));
    if(journal.header.previousInstallation==='none'){await journal.resolve('INSTALL_FAILED_NO_PREVIOUS');return {code:'INSTALL_FAILED_NO_PREVIOUS' as const,automaticRetry:false};}
    let reality;try{reality=inspectRollbackActivation(selection,operationId);}catch{recoverCandidateActivation(selection,operationId);reality=inspectRollbackActivation(selection,operationId);}const activation=reality.root,oldRecord=JSON.parse(readFileSync(reality.oldActive,'utf8')) as {manifestHash:string;build:{buildId:string}},targetRecord=JSON.parse(readFileSync(reality.targetActive,'utf8')) as {manifestHash:string;build:{buildId:string}},manifestRoot=join(selection.root,'installer-staging','manifests',oldRecord.build.buildId);
    if(journal.header.platform.os!==process.platform||journal.header.platform.arch!==process.arch)throw new Error('PLATFORM_IDENTITY_MISMATCH');const verificationTarget={...journal.header.platform,schema:1,protocol:1} as const;
    const old=options.verify(readFileSync(join(manifestRoot,'manifest.json')),readFileSync(join(manifestRoot,'manifest.sig')),verificationTarget);if(old.manifestHash!==oldRecord.manifestHash)throw new Error('OLD_SIGNATURE_INVALID');verifiedRuntime(selection,old);
    const targetRoot=join(selection.root,'installer-staging','manifests',targetRecord.build.buildId),target=options.verify(readFileSync(join(targetRoot,'manifest.json')),readFileSync(join(targetRoot,'manifest.sig')),verificationTarget);if(target.manifestHash!==targetRecord.manifestHash)throw new Error('TARGET_SIGNATURE_INVALID');verifiedRuntime(selection,target);
    const runtimeNames=readdirSync(join(selection.root,'runtime'));if(runtimeNames.some(name=>!['24.20.0','api.json','worker.json','clients'].includes(name)&&!/^selfcheck-[0-9a-f-]{36}\.json$/.test(name)))throw new Error('RUNTIME_OWNERSHIP_UNCONFIRMED');await stopAll(selection,reality.state==='candidate_active'?target:old);await cleanupRuntimeInventory(selection);const snapshot={root:join(selection.root,'installer-staging','snapshot-'+operationId),databasePath:join(selection.root,'installer-staging','snapshot-'+operationId,'snapshot.sqlite'),operationId},record=verifySnapshot(selection,snapshot);
    const dbPath=join(selection.root,'data','jobs.sqlite'),audit=new Database(dbPath,{readonly:true,fileMustExist:true});try{const gate=readGate(audit),write=(audit.prepare('SELECT write_generation AS value FROM maintenance_generation WHERE id=1').get() as {value:number}).value;if(gate.state!=='exclusive'||gate.operationId!==operationId||gate.generation!==failure.generation||write!==failure.writeGeneration||write!==record.writeGeneration||audit.pragma('user_version',{simple:true})!==5)throw new Error('ROLLBACK_FENCE_CHANGED');}finally{audit.close();}const db=new Database(dbPath,{fileMustExist:true});try{db.pragma('wal_checkpoint(TRUNCATE)');db.pragma('journal_mode = DELETE');}finally{db.close();}
    if(existsSync(dbPath+'-wal')||existsSync(dbPath+'-shm'))throw new Error('WAL_NOT_QUIESCED');const failedDb=join(activation,'failed-jobs.sqlite'),temporary=join(selection.root,'data',`.restore-${operationId}.sqlite`);if(existsSync(temporary)||reality.state==='candidate_active'&&existsSync(failedDb)||reality.state==='old_active'&&!existsSync(failedDb))throw new Error('FAILED_DB_REALITY_UNCONFIRMED');copyFileSync(snapshot.databasePath,temporary,1);protectPath(temporary);const flush=openSync(temporary,'r');try{fsyncSync(flush);}finally{closeSync(flush);}const expected=databaseDigest(snapshot.databasePath),actual=databaseDigest(temporary);if(JSON.stringify(expected)!==JSON.stringify(actual))throw new Error('RESTORE_INVALID');const check=new Database(temporary,{readonly:true,fileMustExist:true});try{if(check.pragma('integrity_check',{simple:true})!=='ok'||check.pragma('user_version',{simple:true})!==5)throw new Error('RESTORE_INVALID');}finally{check.close();}const displaced=reality.state==='candidate_active'?failedDb:join(activation,`failed-recovery-${randomUUID()}.sqlite`);renameSync(dbPath,displaced);renameSync(temporary,dbPath);const directory=openSync(join(dbPath,'..'),'r');try{fsyncSync(directory);}finally{closeSync(directory);}if(lstatSync(dbPath).isSymbolicLink()||JSON.stringify(databaseDigest(dbPath))!==JSON.stringify(expected))throw new Error('RESTORE_INVALID');
    if(reality.state==='candidate_active'){renameSync(join(selection.root,'bin'),join(activation,'failed-bin'));renameSync(join(selection.root,'active.json'),join(activation,'failed-active.json'));renameSync(join(activation,'old-bin'),join(selection.root,'bin'));renameSync(join(activation,'old-active.json'),join(selection.root,'active.json'));}assertOwnedLaunchers(selection);await options.fault?.('restored');
    const restored=openDatabase(dbPath);let gate;try{gate=await new SQLiteMaintenanceStore(restored).renewExclusive(operationId,failure.generation,Date.now()+300000);}finally{restored.close();}await options.fault?.('lease_renewed');await journal.clientAdmission('selfcheck',old.manifest.build.buildId);let supervisor=runtimeSupervisor(selection,old,{operationId,generation:gate.generation});await supervisor.start({installationId:journal.header.installationId,role:'api',build:old.manifest.build});await supervisor.start({installationId:journal.header.installationId,role:'worker',build:old.manifest.build});let client=await probe(selection,old,operationId,gate.generation,options.secrets);await client.call('/api/control/maintenance',{action:'exit',operationId,expectedGeneration:gate.generation});
    const deadline=performance.now()+10000;while(performance.now()<deadline){const states=await Promise.all(supervisor.registered().map(i=>supervisor.inspect(i)));if(states.every(s=>s==='exited'))break;await pause(100);}if((await Promise.all(supervisor.registered().map(i=>supervisor.inspect(i)))).some(s=>s!=='exited'))throw new Error('PROCESS_STOP_UNCONFIRMED');
    await journal.clientAdmission('normal_probe',old.manifest.build.buildId);supervisor=runtimeSupervisor(selection,old);await supervisor.start({installationId:journal.header.installationId,role:'api',build:old.manifest.build});await supervisor.start({installationId:journal.header.installationId,role:'worker',build:old.manifest.build});client=await probe(selection,old,null,gate.generation+1,options.secrets);
    const status=await client.status(),statusDb=openDatabase(dbPath);try{const open=readGate(statusDb),value={operationId,stage:'rollback',result:'restored',targetBuild:journal.header.target,actualBuild:old.manifest.build,cleanup:'complete',previousInstallation:'present',checkedAt:await nextProjectionTime(statusDb,'install')};await client.call('/api/control/status-projection',{kind:'install',operationId:null,expectedGeneration:open.generation,value});}finally{statusDb.close();}if(!status.api)throw new Error('ROLLBACK_STATUS_UNCONFIRMED');await journal.resolve('UPGRADE_FAILED_ROLLED_BACK');return {code:'UPGRADE_FAILED_ROLLED_BACK' as const,actualBuild:old.manifest.build,generation:gate.generation+1,automaticRetry:false};
  }catch(error){if(error instanceof RecoveryError)throw error;throw new RecoveryError('HUMAN_RECOVERY_REQUIRED',error instanceof Error?error.message:'RECOVERY_FAILED');}
}
