import Database from 'better-sqlite3';
import {copyFileSync,existsSync,lstatSync,readFileSync,renameSync,openSync,closeSync,fsyncSync,readdirSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {join} from 'node:path';
import {z} from 'zod';
import type {SecretStore} from '../../application/src/ports.js';
import {assertManagedPath,managedPaths,type RootSelection} from '../../platform/src/paths.js';
import {inspectClientHosts} from '../../platform/src/client-host.js';
import {openDatabase,readGate,SQLiteMaintenanceStore} from '../../persistence/src/database.js';
import {runSelfcheck} from '../../../scripts/install/selfcheck.mjs';
import {JOURNAL_STAGES,UpgradeJournal,nextProjectionTime} from './journal.js';
import {readActive,assertOwnedLaunchers,writeInstallerRecord} from './launchers.js';
import {runtimeSupervisor,verifiedInstallerClient,verifiedRuntime,recoverCandidateActivation,inspectRollbackActivation} from './upgrade.js';
import {verifySnapshot} from './snapshot.js';
import type {VerifiedManifest,VerificationTarget} from './verify-manifest.js';
import {protectPath,verifyProtectedPath} from '../../platform/src/permissions.js';
import {databaseDigest} from './snapshot.js';
import {cleanupManaged,cleanupRuntimeInventory} from './cleanup.js';

export class RecoveryError extends Error {
  constructor(readonly code:'HUMAN_RECOVERY_REQUIRED',readonly causeCode:string){
    // Keep the public error bounded while retaining the exact internal cause
    // for recovery receipts and test diagnostics. Never put paths or arbitrary
    // exception text into the thrown message.
    const safe=/^[A-Z0-9_]+$/.test(causeCode)?causeCode:'UNSPECIFIED';
    super(`${code}_${safe}`);
  }
}
const Failure=z.strictObject({operationId:z.uuid(),code:z.string(),generation:z.number().int().nonnegative(),writeGeneration:z.number().int().nonnegative(),projectionWritten:z.boolean().optional(),projectionCode:z.string().optional()});
const CleanupFailure=Failure.extend({code:z.string().regex(/^(?:CLEANUP_PENDING(?:_[A-Z_]+)?|INTERRUPTED)_CLEANED_INTENT$/),projectionWritten:z.boolean(),projectionCode:z.enum(['AUTHENTICATED_ROUTE','INTERRUPTED_PROCESS'])});
const Admission=z.strictObject({operationId:z.uuid(),buildId:z.string().regex(/^[a-f0-9]{64}$/),mode:z.enum(['selfcheck','normal_probe','blocked'])});
const pause=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
function protectedRecord(path:string){const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||stat.size>16384)throw new Error('MAINTENANCE_RECOVERY_REQUIRED');verifyProtectedPath(path);return JSON.parse(readFileSync(path,'utf8'));}
const sha=(value:unknown)=>createHash('sha256').update(typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value)).digest('hex');
type Verify=(bytes:Buffer,signature:Buffer,target:VerificationTarget)=>VerifiedManifest;
export interface InterruptedUpgradeRecoveryPreview {readonly schema:1;readonly reason:'INTERRUPTED_UPDATE';readonly action:'continue'|'rollback';readonly currentVersion:string;readonly targetVersion:string;readonly lastStage:string;readonly lastPhase:'intent'|'done';readonly signedBinding:string;readonly scopeHash:string}
const interruptedPreviews=new WeakMap<object,{selection:RootSelection;verify:Verify;secrets:SecretStore;operationId:string;mode:'continue_cleanup'|'continue_finalize'|'rollback'|'retire'}>();
function protectedFile(path:string,maximum:number){const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||stat.size<1||stat.size>maximum)throw new Error('SIGNED_MANIFEST_MISMATCH');verifyProtectedPath(path);return readFileSync(path);}
function loadBoundManifest(selection:RootSelection,buildId:string,verify:Verify,target:VerificationTarget){const root=join(selection.root,'installer-staging','manifests',buildId);return verify(protectedFile(join(root,'manifest.json'),8*1024*1024),protectedFile(join(root,'manifest.sig'),64),target);}
/** Read-only classification of an abandoned operation. Every displayed action
 * is bound to the signed target, current signed active build and journal tip. */
export async function prepareInterruptedUpgradeRecovery(selection:RootSelection,verify:Verify,secrets:SecretStore):Promise<InterruptedUpgradeRecoveryPreview|null>{
  try{
    const pending=await UpgradeJournal.pending(selection);if(!pending)return null;const last=pending.entries.at(-1);if(!last)throw new Error('INTERRUPTION_BOUNDARY_UNCONFIRMED');
    const targetSpec={...pending.header.platform,schema:1,protocol:1} as const,target=loadBoundManifest(selection,pending.header.target.buildId,verify,targetSpec),active=assertOwnedLaunchers(selection),current=loadBoundManifest(selection,active.build.buildId,verify,targetSpec);if(target.manifestHash!==pending.header.manifestHash||JSON.stringify(target.manifest.build)!==JSON.stringify(pending.header.target)||current.manifestHash!==active.manifestHash)throw new Error('SIGNED_MANIFEST_MISMATCH');verifiedRuntime(selection,current);
    const failurePath=join(selection.root,'installer-staging',`failure-${pending.header.operationId}.json`),failure=existsSync(failurePath)?Failure.parse(protectedRecord(failurePath)):null,index=JOURNAL_STAGES.indexOf(last.stage),preMutation=index<JOURNAL_STAGES.indexOf('quiesced'),cleanupBoundary=last.stage==='cleaned'&&last.phase==='intent'&&pending.entries.length===19,finalizeBoundary=index>=JOURNAL_STAGES.indexOf('cleaned')&&index<=JOURNAL_STAGES.indexOf('complete')&&!cleanupBoundary,rollbackBoundary=index>=JOURNAL_STAGES.indexOf('activated')&&index<=JOURNAL_STAGES.indexOf('feature_verified');
    let mode:'continue_cleanup'|'continue_finalize'|'rollback'|'retire';if(cleanupBoundary)mode='continue_cleanup';else if(finalizeBoundary)mode='continue_finalize';else if(preMutation)mode='retire';else if(rollbackBoundary)mode='rollback';else throw new Error('INTERRUPTION_BOUNDARY_UNCONFIRMED');
    if(preMutation&&pending.entries.length>=6)verifiedRuntime(selection,target);if(mode.startsWith('continue')&&active.manifestHash!==target.manifestHash)throw new Error('ACTIVATION_REALITY_UNCONFIRMED');
    const action=mode.startsWith('continue')?'continue':'rollback',signedBinding=sha({manifestHash:target.manifestHash,currentManifestHash:current.manifestHash,journalHash:pending.journalHash}),scopeHash=sha({contract:'interrupted-upgrade-recovery-v1',installationId:pending.header.installationId,operationId:pending.header.operationId,action,lastStage:last.stage,lastPhase:last.phase,signedBinding,failure:failure?sha(failure):null});
    const preview=Object.freeze({schema:1 as const,reason:'INTERRUPTED_UPDATE' as const,action,currentVersion:active.build.version,targetVersion:target.manifest.build.version,lastStage:last.stage,lastPhase:last.phase,signedBinding,scopeHash});interruptedPreviews.set(preview,{selection,verify,secrets,operationId:pending.header.operationId,mode});return preview;
  }catch(error){if(error instanceof Error&&['UPGRADE_LOCKED','MAINTENANCE_RECOVERY_REQUIRED'].includes(error.message))throw error;throw new RecoveryError('HUMAN_RECOVERY_REQUIRED',error instanceof Error&&/^[A-Z_]+$/.test(error.message)?error.message:'INTERRUPTION_PROOF_FAILED');}
}
async function recordAbruptFailure(selection:RootSelection,operationId:string){const path=assertManagedPath(managedPaths(selection.root),`installer-staging/failure-${operationId}.json`);if(existsSync(path))return;const state=UpgradeJournal.read(selection,operationId),last=state.entries.at(-1);if(!last)throw new Error('INTERRUPTION_BOUNDARY_UNCONFIRMED');const db=openDatabase(assertManagedPath(managedPaths(selection.root),'data/jobs.sqlite'));try{const gate=readGate(db),writeGeneration=(db.prepare('SELECT write_generation AS value FROM maintenance_generation WHERE id=1').get() as {value:number}).value;writeInstallerRecord(path,{operationId,code:`INTERRUPTED_${last.stage.toUpperCase()}_${last.phase.toUpperCase()}`,generation:gate.generation,writeGeneration,projectionWritten:false,projectionCode:'INTERRUPTED_PROCESS'});}finally{db.close();}}
/** Exact one-shot confirmation. A second proof pass occurs before any lock,
 * maintenance, launcher or database mutation. */
export async function confirmInterruptedUpgradeRecovery(preview:InterruptedUpgradeRecoveryPreview,answer:string){
  const context=interruptedPreviews.get(preview),verb=preview.action==='continue'?'CONTINUE':'ROLLBACK';if(!context||answer!==`${verb} ${preview.scopeHash}`)throw new Error('RECOVERY_CONFIRMATION_REQUIRED');interruptedPreviews.delete(preview);const repeated=await prepareInterruptedUpgradeRecovery(context.selection,context.verify,context.secrets);if(!repeated||repeated.scopeHash!==preview.scopeHash)throw new Error('INSTALLATION_RECOVERY_STALE');
  if(context.mode==='retire'){
    const pending=await UpgradeJournal.pending(context.selection),last=pending?.entries.at(-1);if(!pending||pending.header.operationId!==context.operationId||!last||JOURNAL_STAGES.indexOf(last.stage)>=JOURNAL_STAGES.indexOf('quiesced')||existsSync(join(context.selection.root,'installer-staging',`snapshot-${context.operationId}`))||existsSync(join(context.selection.root,'installer-staging',`activation-${context.operationId}`)))throw new Error('INSTALLATION_RECOVERY_STALE');const db=openDatabase(join(context.selection.root,'data','jobs.sqlite'));try{const gate=readGate(db);if(gate.state!=='open'||gate.operationId!==null||gate.generation!==pending.header.generation)throw new Error('INSTALLATION_RECOVERY_STALE');}finally{db.close();}const journal=await UpgradeJournal.recover(context.selection,context.operationId);await journal.resolve('INTERRUPTED_PRE_MUTATION_RETIRED');return{state:'recovered' as const,action:'rollback' as const,code:'INTERRUPTED_PRE_MUTATION_RETIRED' as const,automaticRetry:false as const};
  }
  await recordAbruptFailure(context.selection,context.operationId);if(context.mode==='continue_cleanup')return resumeCleanupUpgrade(context.selection,context.operationId,{verify:context.verify,secrets:context.secrets});if(context.mode==='continue_finalize')return resumeFinalizationUpgrade(context.selection,context.operationId,{verify:context.verify,secrets:context.secrets});return recoverUpgrade(context.selection,context.operationId,{verify:context.verify,secrets:context.secrets});
}
/** Detects only the exact post-activation cleanup failure that the verified rollback engine can recover. */
export function pendingCleanupRecovery(selection:RootSelection){
  const lock=join(selection.root,'installer-staging','update.lock');if(!existsSync(lock))return null;
  try{const admission=Admission.parse(protectedRecord(join(lock,'admission.json'))),failure=CleanupFailure.parse(protectedRecord(join(selection.root,'installer-staging',`failure-${admission.operationId}.json`))),journal=UpgradeJournal.read(selection,admission.operationId),last=journal.entries.at(-1);if(failure.operationId!==admission.operationId||admission.mode!=='selfcheck'||journal.recovery||journal.header.previousInstallation!=='present'||last?.stage!=='cleaned'||last.phase!=='intent'||journal.entries.length!==19)throw new Error('MAINTENANCE_RECOVERY_REQUIRED');return admission.operationId;}catch(error){if(error instanceof Error&&error.message==='MAINTENANCE_RECOVERY_REQUIRED')throw error;throw new Error('MAINTENANCE_RECOVERY_REQUIRED');}
}
async function stopAll(selection:RootSelection,manifest:VerifiedManifest){const s=runtimeSupervisor(selection,manifest);for(const i of s.registered().reverse()){const state=await s.inspect(i);if(state==='running')await s.stop(i);else if(state!=='exited')throw new RecoveryError('HUMAN_RECOVERY_REQUIRED',s.inspectionCause(i.role)??'PROCESS_OWNERSHIP_UNCONFIRMED');}for(const h of await inspectClientHosts(selection))if(h.state!=='exited')throw new RecoveryError('HUMAN_RECOVERY_REQUIRED','HOST_OWNERSHIP_UNCONFIRMED');}
async function probe(selection:RootSelection,manifest:VerifiedManifest,operationId:string|null,generation:number,store:SecretStore){const runtime=verifiedRuntime(selection,manifest),client=verifiedInstallerClient(selection,manifest),result=await runSelfcheck({selection,managedNode:runtime.managedNode,cliEntry:runtime.entries.cli,mcpEntry:runtime.entries.mcp,manifestPath:runtime.manifestPath,operationId,generation,installerClient:client,releaseObservation:manifest.evidence==='verified_release_manifest'?{build:manifest.manifest.build,manifestHash:manifest.manifestHash,evidence:'verified_release_manifest',checkedAt:new Date().toISOString()}:undefined});if(!result?.matched||result.featureResult!=='pass'){const code=result&&'code'in result?result.code:null,detail=typeof code==='string'&&/^[A-Z_]+$/.test(code)?`_${code}`:'';throw new RecoveryError('HUMAN_RECOVERY_REQUIRED',`ROLLBACK_SELFCHECK_FAILED${detail}`);}return client;}
/** Stop the operation-scoped generation through its authenticated control routes.
 *
 * Waiting for a stale generation to notice the incremented maintenance fence
 * relied on a heartbeat/scheduler race and could exceed the bounded recovery
 * window.  Explicit shutdown keeps the same fail-closed ownership checks while
 * making the lifecycle boundary deterministic.
 */
async function stopGeneration(supervisor:ReturnType<typeof runtimeSupervisor>){
  for(const identity of supervisor.registered().reverse()){
    const state=await supervisor.inspect(identity);
    if(state==='running')await supervisor.stop(identity);
    else if(state!=='exited')throw new Error('PROCESS_OWNERSHIP_UNCONFIRMED');
  }
}

/** Continues the exact durable cleaned/intent boundary instead of rolling a feature-verified target back. */
export async function resumeCleanupUpgrade(selection:RootSelection,operationId:string,options:{verify:(bytes:Buffer,signature:Buffer,target:VerificationTarget)=>VerifiedManifest;secrets:SecretStore}){
  try{
    const journal=await UpgradeJournal.recover(selection,operationId),failure=CleanupFailure.parse(protectedRecord(join(selection.root,'installer-staging',`failure-${operationId}.json`))),state=UpgradeJournal.read(selection,operationId),last=state.entries.at(-1);if(last?.stage!=='cleaned'||last.phase!=='intent'||state.entries.length!==19||failure.operationId!==operationId)throw new Error('CLEANUP_RESUME_BOUNDARY_INVALID');
    const activation=join(selection.root,'installer-staging','activation-'+operationId),active=readActive(selection),inactivePath=join(activation,'inactive.json'),oldPath=existsSync(join(activation,'old-active.json'))?join(activation,'old-active.json'):inactivePath;if(!existsSync(oldPath))throw new Error('CLEANUP_RESUME_BOUNDARY_INVALID');const oldRecord=protectedRecord(oldPath) as {manifestHash?:unknown;build?:{buildId?:unknown}},oldBuild=z.string().regex(/^[a-f0-9]{64}$/).parse(oldRecord.build?.buildId),oldHash=z.string().regex(/^[a-f0-9]{64}$/).parse(oldRecord.manifestHash);
    if(journal.header.platform.os!==process.platform||journal.header.platform.arch!==process.arch||active.manifestHash!==journal.header.manifestHash||active.build.buildId!==journal.header.target.buildId)throw new Error('PLATFORM_IDENTITY_MISMATCH');const targetSpec={...journal.header.platform,schema:1,protocol:1} as const,load=(buildId:string)=>{const root=join(selection.root,'installer-staging','manifests',buildId);return options.verify(readFileSync(join(root,'manifest.json')),readFileSync(join(root,'manifest.sig')),targetSpec);},target=load(active.build.buildId),old=load(oldBuild);if(target.manifestHash!==active.manifestHash||old.manifestHash!==oldHash)throw new Error('SIGNED_MANIFEST_MISMATCH');verifiedRuntime(selection,target);verifiedRuntime(selection,old);
    const snapshot={root:join(selection.root,'installer-staging','snapshot-'+operationId),databasePath:join(selection.root,'installer-staging','snapshot-'+operationId,'snapshot.sqlite'),operationId},record=verifySnapshot(selection,snapshot),dbPath=join(selection.root,'data','jobs.sqlite'),db=openDatabase(dbPath);try{const gate=readGate(db),write=(db.prepare('SELECT write_generation AS value FROM maintenance_generation WHERE id=1').get() as {value:number}).value;if(gate.state!=='exclusive'||gate.operationId!==operationId||gate.generation!==failure.generation||write!==failure.writeGeneration||write!==record.writeGeneration)throw new Error('ROLLBACK_FENCE_CHANGED');}finally{db.close();}
    let supervisor=runtimeSupervisor(selection,target,{operationId,generation:failure.generation}),states=await Promise.all(supervisor.registered().map(i=>supervisor.inspect(i)));if(states.some(s=>s==='unknown'))throw new Error('PROCESS_OWNERSHIP_UNCONFIRMED');if(states.every(s=>s==='exited')){await supervisor.start({installationId:journal.header.installationId,role:'api',build:target.manifest.build});await supervisor.start({installationId:journal.header.installationId,role:'worker',build:target.manifest.build});}else if(states.some(s=>s!=='running'))throw new Error('PROCESS_OWNERSHIP_UNCONFIRMED');let client=verifiedInstallerClient(selection,target);
    const cleaned=await cleanupManaged({selection,operationId,currentManifest:target,oldManifest:old});if(!cleaned.complete)throw new Error(cleaned.code);await journal.append('cleaned','done');await journal.append('reopened','intent');await stopGeneration(supervisor);const reopened=openDatabase(dbPath);try{await new SQLiteMaintenanceStore(reopened).exitMaintenance(operationId,failure.generation);}finally{reopened.close();}await journal.clientAdmission('normal_probe',target.manifest.build.buildId);supervisor=runtimeSupervisor(selection,target);await supervisor.start({installationId:journal.header.installationId,role:'api',build:target.manifest.build});await supervisor.start({installationId:journal.header.installationId,role:'worker',build:target.manifest.build});client=verifiedInstallerClient(selection,target);await journal.append('reopened','done');await journal.append('normal_verified','intent');client=await probe(selection,target,null,failure.generation+1,options.secrets);await journal.append('normal_verified','done');await journal.append('complete','intent');const status=await client.status();if(status.api?.build?.buildId!==target.manifest.build.buildId||status.worker?.build?.buildId!==target.manifest.build.buildId||status.selfcheck?.featureResult!=='pass')throw new Error('FEATURE_SELFCHECK_FAILED');await journal.append('complete','done');const projectionDb=openDatabase(dbPath);try{const gate=readGate(projectionDb),value={operationId,stage:'complete',result:'succeeded',targetBuild:journal.header.target,actualBuild:target.manifest.build,cleanup:'complete',previousInstallation:'present',checkedAt:await nextProjectionTime(projectionDb,'install')};await client.call('/api/control/status-projection',{kind:'install',operationId:null,expectedGeneration:gate.generation,value});}finally{projectionDb.close();}await journal.release();return{state:'complete' as const,operationId,generation:failure.generation+1,build:target.manifest.build,cleanup:'complete' as const,resumed:true as const};
  }catch(error){if(error instanceof RecoveryError)throw error;throw new RecoveryError('HUMAN_RECOVERY_REQUIRED',error instanceof Error&&/^[A-Z_]+$/.test(error.message)?error.message:'CLEANUP_RESUME_FAILED');}
}

/** Re-establishes one deterministic normal target generation after cleanup has
 * become durable, then completes only the missing journal suffix. Repeating an
 * interrupted continuation is safe because the hash-chain position and gate
 * generation are re-read before each append. */
export async function resumeFinalizationUpgrade(selection:RootSelection,operationId:string,options:{verify:Verify;secrets:SecretStore}){
  try{
    const journal=await UpgradeJournal.recover(selection,operationId),failure=Failure.parse(protectedRecord(join(selection.root,'installer-staging',`failure-${operationId}.json`))),initial=UpgradeJournal.read(selection,operationId),length=initial.entries.length,last=initial.entries.at(-1);if(length<20||length>26||!last||JOURNAL_STAGES.indexOf(last.stage)<JOURNAL_STAGES.indexOf('cleaned')||last.stage==='cleaned'&&last.phase==='intent'||failure.operationId!==operationId||journal.header.previousInstallation!=='present'||![journal.header.generation,journal.header.generation+1].includes(failure.generation))throw new Error('FINALIZATION_RESUME_BOUNDARY_INVALID');
    const targetSpec={...journal.header.platform,schema:1,protocol:1} as const,target=loadBoundManifest(selection,journal.header.target.buildId,options.verify,targetSpec),active=assertOwnedLaunchers(selection);if(target.manifestHash!==journal.header.manifestHash||active.manifestHash!==target.manifestHash||active.build.buildId!==target.manifest.build.buildId)throw new Error('SIGNED_MANIFEST_MISMATCH');verifiedRuntime(selection,target);
    if(UpgradeJournal.read(selection,operationId).entries.length===20)await journal.append('reopened','intent');await stopAll(selection,target);await cleanupRuntimeInventory(selection);const dbPath=join(selection.root,'data','jobs.sqlite'),db=openDatabase(dbPath);let generation:number;try{const gate=readGate(db),write=(db.prepare('SELECT write_generation AS value FROM maintenance_generation WHERE id=1').get() as {value:number}).value;if(write!==failure.writeGeneration)throw new Error('ROLLBACK_FENCE_CHANGED');if(gate.state==='exclusive'&&gate.operationId===operationId&&gate.generation===journal.header.generation){await new SQLiteMaintenanceStore(db).exitMaintenance(operationId,journal.header.generation);generation=journal.header.generation+1;}else if(gate.state==='open'&&gate.operationId===null&&gate.generation===journal.header.generation+1)generation=gate.generation;else throw new Error('FINALIZATION_GATE_INVALID');}finally{db.close();}
    await journal.clientAdmission('normal_probe',target.manifest.build.buildId);let supervisor=runtimeSupervisor(selection,target);await supervisor.start({installationId:journal.header.installationId,role:'api',build:target.manifest.build});await supervisor.start({installationId:journal.header.installationId,role:'worker',build:target.manifest.build});let state=UpgradeJournal.read(selection,operationId);if(state.entries.length===21)await journal.append('reopened','done');state=UpgradeJournal.read(selection,operationId);if(state.entries.length===22)await journal.append('normal_verified','intent');const client=await probe(selection,target,null,generation,options.secrets);state=UpgradeJournal.read(selection,operationId);if(state.entries.length===23)await journal.append('normal_verified','done');state=UpgradeJournal.read(selection,operationId);if(state.entries.length===24)await journal.append('complete','intent');const status=await client.status();if(status.api?.build?.buildId!==target.manifest.build.buildId||status.worker?.build?.buildId!==target.manifest.build.buildId||status.selfcheck?.featureResult!=='pass')throw new Error('FEATURE_SELFCHECK_FAILED');state=UpgradeJournal.read(selection,operationId);if(state.entries.length===25)await journal.append('complete','done');if(UpgradeJournal.read(selection,operationId).entries.length!==26)throw new Error('FINALIZATION_RESUME_BOUNDARY_INVALID');
    const projection=openDatabase(dbPath);try{const gate=readGate(projection),value={operationId,stage:'complete',result:'succeeded',targetBuild:journal.header.target,actualBuild:target.manifest.build,cleanup:'complete',previousInstallation:'present',checkedAt:await nextProjectionTime(projection,'install')};await client.call('/api/control/status-projection',{kind:'install',operationId:null,expectedGeneration:gate.generation,value});}finally{projection.close();}await journal.release();return{state:'complete' as const,operationId,generation,build:target.manifest.build,cleanup:'complete' as const,resumed:true as const};
  }catch(error){if(error instanceof RecoveryError)throw error;throw new RecoveryError('HUMAN_RECOVERY_REQUIRED',error instanceof Error&&/^[A-Z_]+$/.test(error.message)?error.message:'FINALIZATION_RESUME_FAILED');}
}

export async function recoverUpgrade(selection:RootSelection,operationId:string,options:{verify:(bytes:Buffer,signature:Buffer,target:VerificationTarget)=>VerifiedManifest;secrets:SecretStore;fault?:(stage:'restored'|'lease_renewed')=>Promise<void>}){
  try{
    const journal=await UpgradeJournal.recover(selection,operationId),failure=Failure.parse(JSON.parse(readFileSync(join(selection.root,'installer-staging',`failure-${operationId}.json`),'utf8')));
    if(journal.header.previousInstallation==='none'){await journal.resolve('INSTALL_FAILED_NO_PREVIOUS');return {code:'INSTALL_FAILED_NO_PREVIOUS' as const,automaticRetry:false};}
    let reality;try{reality=inspectRollbackActivation(selection,operationId);}catch{recoverCandidateActivation(selection,operationId);reality=inspectRollbackActivation(selection,operationId);}const activation=reality.root,oldRecord=JSON.parse(readFileSync(reality.oldActive,'utf8')) as {manifestHash:string;build:{buildId:string}},targetRecord=JSON.parse(readFileSync(reality.targetActive,'utf8')) as {manifestHash:string;build:{buildId:string}},manifestRoot=join(selection.root,'installer-staging','manifests',oldRecord.build.buildId);
    if(journal.header.platform.os!==process.platform||journal.header.platform.arch!==process.arch)throw new Error('PLATFORM_IDENTITY_MISMATCH');const verificationTarget={...journal.header.platform,schema:1,protocol:1} as const;
    const old=options.verify(readFileSync(join(manifestRoot,'manifest.json')),readFileSync(join(manifestRoot,'manifest.sig')),verificationTarget);if(old.manifestHash!==oldRecord.manifestHash)throw new Error('OLD_SIGNATURE_INVALID');verifiedRuntime(selection,old);
    const targetRoot=join(selection.root,'installer-staging','manifests',targetRecord.build.buildId),target=options.verify(readFileSync(join(targetRoot,'manifest.json')),readFileSync(join(targetRoot,'manifest.sig')),verificationTarget);if(target.manifestHash!==targetRecord.manifestHash)throw new Error('TARGET_SIGNATURE_INVALID');verifiedRuntime(selection,target);
    const runtimeNames=readdirSync(join(selection.root,'runtime'));if(runtimeNames.some(name=>!['24.20.0','api.json','worker.json','clients'].includes(name)&&!/^selfcheck-[0-9a-f-]{36}\.json$/.test(name)))throw new Error('RUNTIME_OWNERSHIP_UNCONFIRMED');await stopAll(selection,reality.state==='candidate_active'?target:old);await cleanupRuntimeInventory(selection);const snapshot={root:join(selection.root,'installer-staging','snapshot-'+operationId),databasePath:join(selection.root,'installer-staging','snapshot-'+operationId,'snapshot.sqlite'),operationId},record=verifySnapshot(selection,snapshot);
    const dbPath=join(selection.root,'data','jobs.sqlite'),audit=new Database(dbPath,{readonly:true,fileMustExist:true});try{const gate=readGate(audit),write=(audit.prepare('SELECT write_generation AS value FROM maintenance_generation WHERE id=1').get() as {value:number}).value;if(gate.state!=='exclusive'||gate.operationId!==operationId||gate.generation!==failure.generation||write!==failure.writeGeneration||write!==record.writeGeneration||audit.pragma('user_version',{simple:true})!==5)throw new Error('ROLLBACK_FENCE_CHANGED');}finally{audit.close();}const db=new Database(dbPath,{fileMustExist:true});try{db.pragma('wal_checkpoint(TRUNCATE)');db.pragma('journal_mode = DELETE');}finally{db.close();}
    if(existsSync(dbPath+'-wal')||existsSync(dbPath+'-shm'))throw new Error('WAL_NOT_QUIESCED');const failedDb=join(activation,'failed-jobs.sqlite'),temporary=join(selection.root,'data',`.restore-${operationId}.sqlite`);if(existsSync(temporary)||reality.state==='candidate_active'&&existsSync(failedDb)||reality.state==='old_active'&&!existsSync(failedDb))throw new Error('FAILED_DB_REALITY_UNCONFIRMED');copyFileSync(snapshot.databasePath,temporary,1);protectPath(temporary);const flush=openSync(temporary,'r');try{fsyncSync(flush);}finally{closeSync(flush);}const expected=databaseDigest(snapshot.databasePath),actual=databaseDigest(temporary);if(JSON.stringify(expected)!==JSON.stringify(actual))throw new Error('RESTORE_INVALID');const check=new Database(temporary,{readonly:true,fileMustExist:true});try{if(check.pragma('integrity_check',{simple:true})!=='ok'||check.pragma('user_version',{simple:true})!==5)throw new Error('RESTORE_INVALID');}finally{check.close();}const displaced=reality.state==='candidate_active'?failedDb:join(activation,`failed-recovery-${randomUUID()}.sqlite`);renameSync(dbPath,displaced);renameSync(temporary,dbPath);const directory=openSync(join(dbPath,'..'),'r');try{fsyncSync(directory);}finally{closeSync(directory);}if(lstatSync(dbPath).isSymbolicLink()||JSON.stringify(databaseDigest(dbPath))!==JSON.stringify(expected))throw new Error('RESTORE_INVALID');
    if(reality.state==='candidate_active'){renameSync(join(selection.root,'bin'),join(activation,'failed-bin'));renameSync(join(selection.root,'active.json'),join(activation,'failed-active.json'));renameSync(join(activation,'old-bin'),join(selection.root,'bin'));renameSync(join(activation,'old-active.json'),join(selection.root,'active.json'));}assertOwnedLaunchers(selection);await options.fault?.('restored');
    const restored=openDatabase(dbPath);let gate;try{gate=await new SQLiteMaintenanceStore(restored).renewExclusive(operationId,failure.generation,Date.now()+300000);}finally{restored.close();}await options.fault?.('lease_renewed');await journal.clientAdmission('selfcheck',old.manifest.build.buildId);let supervisor=runtimeSupervisor(selection,old,{operationId,generation:gate.generation});await supervisor.start({installationId:journal.header.installationId,role:'api',build:old.manifest.build});await supervisor.start({installationId:journal.header.installationId,role:'worker',build:old.manifest.build});let client=await probe(selection,old,operationId,gate.generation,options.secrets);await stopGeneration(supervisor);const reopened=openDatabase(dbPath);try{await new SQLiteMaintenanceStore(reopened).exitMaintenance(operationId,gate.generation);}finally{reopened.close();}
    await journal.clientAdmission('normal_probe',old.manifest.build.buildId);supervisor=runtimeSupervisor(selection,old);await supervisor.start({installationId:journal.header.installationId,role:'api',build:old.manifest.build});await supervisor.start({installationId:journal.header.installationId,role:'worker',build:old.manifest.build});client=await probe(selection,old,null,gate.generation+1,options.secrets);
    const status=await client.status(),statusDb=openDatabase(dbPath);try{const open=readGate(statusDb),value={operationId,stage:'rollback',result:'restored',targetBuild:journal.header.target,actualBuild:old.manifest.build,cleanup:'complete',previousInstallation:'present',checkedAt:await nextProjectionTime(statusDb,'install')};await client.call('/api/control/status-projection',{kind:'install',operationId:null,expectedGeneration:open.generation,value});}finally{statusDb.close();}if(!status.api)throw new Error('ROLLBACK_STATUS_UNCONFIRMED');await journal.resolve('UPGRADE_FAILED_ROLLED_BACK');return {code:'UPGRADE_FAILED_ROLLED_BACK' as const,actualBuild:old.manifest.build,generation:gate.generation+1,automaticRetry:false};
  }catch(error){if(error instanceof RecoveryError)throw error;throw new RecoveryError('HUMAN_RECOVERY_REQUIRED',error instanceof Error?error.message:'RECOVERY_FAILED');}
}
