import {expect,it} from 'vitest';
import {createHash,randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync,mkdirSync,realpathSync,existsSync,chmodSync,renameSync,symlinkSync,unlinkSync} from 'node:fs';
import {join} from 'node:path';
import {gzipSync} from 'node:zlib';
import {execFileSync,spawn} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {Client} from '@modelcontextprotocol/client';
import {StdioClientTransport} from '@modelcontextprotocol/client/stdio';
import {observeProcess} from '../../packages/platform/src/processes.js';
import {createHarness} from '../../packages/test-support/src/harness.js';
import {protectPath} from '../../packages/platform/src/permissions.js';
import {initializeInstallation,readInstallation} from '../../packages/platform/src/installation.js';
import {signSyntheticManifests} from '../../scripts/build/synthetic-sign.mjs';
import {createFixtureVerifier} from '../../packages/installer/src/verify-manifest.js';
import {createInstallPreview,confirmInstallPreview} from '../../packages/installer/src/preview.js';
import {installConfirmed} from '../../packages/installer/src/install.js';
import {readActive,launcherRegistration} from '../../packages/installer/src/launchers.js';
const sha=(bytes:Buffer|string)=>createHash('sha256').update(bytes).digest('hex');
function tar(files:{path:string;data:Buffer}[]){const chunks:Buffer[]=[];for(const f of files){const h=Buffer.alloc(512);h.write(f.path,0,100);h.write('0000600\0',100);h.write(f.data.length.toString(8).padStart(11,'0')+'\0',124);h.fill(32,148,156);h[156]=48;h.write('ustar\0',257);h.write('00',263);h.write(h.reduce((n,b)=>n+b,0).toString(8).padStart(6,'0')+'\0 ',148);chunks.push(h,f.data,Buffer.alloc((512-f.data.length%512)%512));}chunks.push(Buffer.alloc(1024));return gzipSync(Buffer.concat(chunks));}
async function fixture(parent:string){
  const require=createRequire(import.meta.url),program=Buffer.from(`process.stdout.write(JSON.stringify({entry:require('node:path').basename(require('node:path').dirname(require('node:path').dirname(__filename))),args:process.argv.slice(2)})+'\\n');`),mcp=Buffer.from(`const {McpServer}=require(${JSON.stringify(require.resolve('@modelcontextprotocol/server'))});const {StdioServerTransport}=require(${JSON.stringify(require.resolve('@modelcontextprotocol/server/stdio'))});const {z}=require(${JSON.stringify(require.resolve('zod'))});const server=new McpServer({name:'synthetic-launcher',version:'0.1.0'});server.registerTool('fixture_status',{inputSchema:z.strictObject({})},async()=>({content:[{type:'text',text:'synthetic-transport-only'}]}));void server.connect(new StdioServerTransport());`),programFiles=[{path:'apps/cli/src/main.js',data:program},{path:'apps/mcp/src/main.js',data:mcp}],node=readFileSync(process.execPath),browser=Buffer.from('synthetic-browser-only');
  const parts=[{name:'program.tar.gz',role:'program',format:'tar.gz',data:tar(programFiles),files:programFiles},{name:'node',role:'node',format:'file',data:node,files:[{path:'bin/node',data:node,executable:true}]},{name:'browser',role:'browser',format:'file',data:browser,files:[{path:'synthetic-browser.txt',data:browser}]}];
  const manifest={schema:1,product:'autoed-rebuild',build:{version:'0.1.0-beta.1',buildId:'a'.repeat(64),commit:'b'.repeat(40),tree:'c'.repeat(40),dependencyHash:'d'.repeat(64),protocol:1,schemaMin:1,schemaMax:1,capabilities:['echo']},target:{os:'darwin',arch:'arm64',minVersion:'14.0.0'},dependencies:{node:'24.20.0',playwright:'1.62.1',browserRevision:'1234',browserVersion:'151.0.7922.34'},artifacts:parts.map(p=>({name:p.name,role:p.role,format:p.format,url:'https://github.com/returdex/AutoED/releases/download/0.1.0-beta.1/'+p.name,sha256:sha(p.data),bytes:p.data.length,unpackedBytes:p.files.reduce((n,f)=>n+f.data.length,0),files:p.files.map(({data,...f})=>({...f,bytes:data.length,sha256:sha(data)}))})),dependencySources:[{name:'node',version:'24.20.0',url:'https://nodejs.org/dist/v24.20.0/node-v24.20.0-darwin-arm64.tar.gz',integrity:'sha256-'+'e'.repeat(64)}],tests:{synthetic:'pass',integration:'pass',macosNative:'not_run',windowsNative:'not_run',human:'not_run'}};
  const bytes=Buffer.from(JSON.stringify(manifest)),signed=await signSyntheticManifests(parent,[bytes]);return {manifestBytes:bytes,signature:Buffer.from(signed.signatures[0],'base64'),publicKey:signed.publicKey,fingerprint:signed.fingerprint,verified:createFixtureVerifier(signed.publicKey,signed.fingerprint)(bytes,Buffer.from(signed.signatures[0],'base64'),{os:'darwin',arch:'arm64',version:'26.5.2',schema:1,protocol:1}),archives:Object.fromEntries(parts.map(p=>[p.name,p.data]))};
}
function memoryStore(){const entries=new Map<string,string>();let writes=0;return {get:async(id:string,name:string)=>entries.get(id+':'+name)??null,set:async(id:string,name:string,value:string)=>{writes++;entries.set(id+':'+name,value);},delete:async(id:string,name:string)=>{entries.delete(id+':'+name);},writes:()=>writes};}
it('denied, forged or stale scope confirmation and invalid installation UUID cause zero managed changes',async()=>{
  const h=createHarness();try{const parent=realpathSync(h.root);protectPath(parent);const selection={root:join(parent,'new'),parent,excludedRoots:[]},f=await fixture(parent),store=memoryStore(),preview=createInstallPreview(f.verified,selection);
    expect(()=>confirmInstallPreview(preview,'no')).toThrow('CONFIRMATION_REQUIRED');await expect(installConfirmed(preview,{scopeHash:preview.scopeHash} as never,{store,archives:f.archives})).rejects.toThrow('CONFIRMATION_REQUIRED');expect(existsSync(selection.root)).toBe(false);
    const confirmation=confirmInstallPreview(preview,'INSTALL '+preview.scopeHash);chmodSync(parent,0o750);await expect(installConfirmed(preview,confirmation,{store,archives:f.archives})).rejects.toThrow('REPREVIEW_REQUIRED');chmodSync(parent,0o700);expect(existsSync(selection.root)).toBe(false);
    await expect(initializeInstallation(selection,store,'not-a-uuid')).rejects.toThrow();expect(existsSync(selection.root)).toBe(false);expect(store.writes()).toBe(0);
  }finally{await h.cleanup();}
});
it('confirmed installation binds the actual ID, stages immutable bytes and launches independently from spaces/Chinese paths',async()=>{
  const h=createHarness();let safeCleanup=true;try{const base=realpathSync(h.root);protectPath(base);const parent=join(base,'空 格 %!');mkdirSync(parent,{mode:0o700});protectPath(parent);const selection={root:join(parent,'AutoED-Rebuild'),parent,excludedRoots:[]},f=await fixture(base),store=memoryStore(),preview=createInstallPreview(f.verified,selection),confirmation=confirmInstallPreview(preview,'INSTALL '+preview.scopeHash);
    const result=await installConfirmed(preview,confirmation,{store,archives:f.archives});expect(result.state).toBe('staged');expect(readInstallation(selection).installationId).toBe(preview.installationId);expect(readInstallation(selection).credentials.every(c=>c.scope.installationId===preview.installationId)).toBe(true);expect(readActive(selection).manifestHash).toBe(f.verified.manifestHash);
    const registration=launcherRegistration(selection);expect(registration.name).toBe('autoed-rebuild-m1');expect(registration.args).toEqual(['mcp']);const output=execFileSync(registration.command,['status'],{cwd:base,env:{PATH:'/usr/bin:/bin',NODE_OPTIONS:'--require=/nonexistent-canary'},encoding:'utf8',timeout:10000});expect(JSON.parse(output)).toEqual({entry:'cli',args:['--root',selection.root,'--parent',parent,'status']});
    const transport=new StdioClientTransport({command:registration.command,args:[...registration.args],cwd:base,env:{PATH:'/usr/bin:/bin'},stderr:'pipe'}),client=new Client({name:'installer-test',version:'0.1.0'});safeCleanup=false;let pid:number|null=null;try{await client.connect(transport);pid=transport.pid;expect(pid).not.toBeNull();const result=await client.callTool({name:'fixture_status',arguments:{}},{timeout:5000});expect(JSON.stringify(result)).toContain('synthetic-transport-only');}finally{pid??=transport.pid;await client.close();await transport.close();if(pid){for(let i=0;i<20;i++){if(await observeProcess(pid)===null){safeCleanup=true;break;}await new Promise(resolve=>setTimeout(resolve,100));}}else safeCleanup=true;if(!safeCleanup)throw new Error('HUMAN_ACTION_REQUIRED: owned MCP exit unconfirmed; fixture preserved');}
    const retained=join(selection.root,'data','retained.txt');writeFileSync(retained,'retained');await installConfirmed(preview,confirmation,{store,archives:f.archives});expect(store.writes()).toBe(4);expect(readFileSync(retained,'utf8')).toBe('retained');expect(existsSync(join(selection.root,'provisioning.json'))).toBe(true);
    const again=createInstallPreview(f.verified,selection);await expect(installConfirmed(again,confirmInstallPreview(again,'INSTALL '+again.scopeHash),{store,archives:f.archives})).rejects.toThrow('UPGRADE_ENGINE_REQUIRED');
    const activePath=join(selection.root,'active.json'),savedActive=readFileSync(activePath),activeRecord=JSON.parse(savedActive.toString());expect(activeRecord.artifactSha256).toMatch(/^[a-f0-9]{64}$/);writeFileSync(activePath,JSON.stringify({...activeRecord,manifestHash:'0'.repeat(64)}));expect(()=>execFileSync(registration.command,['status'],{timeout:5000,stdio:'pipe'})).toThrow();writeFileSync(activePath,savedActive);
    const cliPath=join(preview.paths.program,'apps/cli/src/main.js'),savedCLI=readFileSync(cliPath);writeFileSync(cliPath,"process.stdout.write('UNVERIFIED')");let failedOutput='';try{execFileSync(registration.command,['status'],{timeout:5000,stdio:'pipe'});}catch(error){failedOutput=String((error as {stdout:Buffer}).stdout);}expect(failedOutput).toBe('');writeFileSync(cliPath,savedCLI);
    writeFileSync(registration.command,'unknown replacement');await expect(installConfirmed(preview,confirmation,{store,archives:f.archives})).rejects.toThrow('ENTRY_OWNERSHIP_UNCONFIRMED');
  }finally{if(safeCleanup)await h.cleanup();}
},30000);
it('inventory refuses a runtime parent symlink before reading outside the selected installation',async()=>{
  const h=createHarness();try{const parent=realpathSync(h.root);protectPath(parent);const selection={root:join(parent,'managed'),parent,excludedRoots:[]},store=memoryStore(),f=await fixture(parent);await initializeInstallation(selection,store,randomUUID());const outside=join(parent,'outside');mkdirSync(outside,{mode:0o700});protectPath(outside);writeFileSync(join(outside,'api.json'),'not an installation record',{mode:0o000});renameSync(join(selection.root,'runtime'),join(selection.root,'runtime.saved'));symlinkSync(outside,join(selection.root,'runtime'));
    expect(()=>createInstallPreview(f.verified,selection)).toThrow('UNSAFE_PATH');unlinkSync(join(selection.root,'runtime'));renameSync(join(selection.root,'runtime.saved'),join(selection.root,'runtime'));chmodSync(join(outside,'api.json'),0o600);expect(readFileSync(join(outside,'api.json'),'utf8')).toBe('not an installation record');expect(store.writes()).toBe(4);
  }finally{await h.cleanup();}
});
it('actual compiled installer CLI keeps preview and explicit confirmation in one process with the same installation ID',async()=>{
  const h=createHarness();let safeCleanup=true;try{const parent=realpathSync(h.root);protectPath(parent);const f=await fixture(parent),compiled=join(parent,'compiled');execFileSync(process.execPath,['node_modules/typescript/bin/tsc','--outDir',compiled],{timeout:30000,stdio:'pipe'});writeFileSync(join(compiled,'package.json'),JSON.stringify({type:'module'}));symlinkSync(realpathSync('node_modules'),join(compiled,'node_modules'),'dir');
    const stage=join(parent,'stage');mkdirSync(stage,{mode:0o700});protectPath(stage);const manifestPath=join(stage,'release-manifest.json'),signaturePath=join(stage,'release-manifest.sig');writeFileSync(manifestPath,f.manifestBytes,{mode:0o600});writeFileSync(signaturePath,f.signature,{mode:0o600});protectPath(manifestPath);protectPath(signaturePath);const sources:Record<string,string>={};for(const [name,bytes]of Object.entries(f.archives)){sources[name]=join(stage,name);writeFileSync(sources[name]!,bytes,{mode:0o600});}
    const entry=join(compiled,'fixture-installer.mjs');writeFileSync(entry,`import {runInstallerCLI,installConfirmed} from './packages/installer/src/install.js';import {createFixtureVerifier} from './packages/installer/src/verify-manifest.js';import {readFileSync} from 'node:fs';const values=new Map();const store={get:async(id,name)=>values.get(id+name)??null,set:async(id,name,value)=>{values.set(id+name,value)},delete:async(id,name)=>{values.delete(id+name)}};await runInstallerCLI({execute:installConfirmed,verify:createFixtureVerifier(${JSON.stringify(f.publicKey)},${JSON.stringify(f.fingerprint)}),store,acquire:async()=>Object.fromEntries(Object.entries(${JSON.stringify(sources)}).map(([name,path])=>[name,readFileSync(path)]))}).catch(error=>{process.stderr.write(error.message+'\\n');process.exitCode=1});`);
    for(const approve of [false,true]){const root=join(parent,approve?'approved':'denied');safeCleanup=false;const child=spawn(process.execPath,[entry,'--preview','--manifest',manifestPath,'--signature',signaturePath,'--root',root],{cwd:parent,env:{PATH:'/usr/bin:/bin'},stdio:['pipe','pipe','pipe']});let output='',pending='',stderr='',previewId='',replied=false;child.stdout.on('data',chunk=>{output+=chunk;pending+=chunk;if(output.length>65536){child.kill('SIGTERM');return;}let newline;while((newline=pending.indexOf('\n'))>=0){const line=pending.slice(0,newline);pending=pending.slice(newline+1);const item=JSON.parse(line);if(item.type==='install_preview'&&!replied){replied=true;previewId=item.preview.installationId;child.stdin.write((approve?'INSTALL '+item.preview.scopeHash:'no')+'\n');}}});child.stderr.on('data',chunk=>{stderr=(stderr+chunk).slice(-4096);});
      const code=await new Promise<number|null>((resolve,reject)=>{const timer=setTimeout(()=>{child.kill('SIGTERM');},20000),force=setTimeout(()=>{child.kill('SIGKILL');},25000),deadline=setTimeout(()=>reject(new Error('HUMAN_ACTION_REQUIRED: owned installer exit unconfirmed')),30000);child.once('error',error=>{if(child.pid===undefined)safeCleanup=true;reject(error);});child.once('close',code=>{clearTimeout(timer);clearTimeout(force);clearTimeout(deadline);safeCleanup=true;resolve(code);});});expect(code,stderr).toBe(approve?0:1);expect(previewId.length).toBe(36);expect(existsSync(root)).toBe(approve);if(approve){expect(readInstallation({root,parent,excludedRoots:[]}).installationId).toBe(previewId);expect(output).toContain('"state":"staged"');}else expect(stderr).toContain('CONFIRMATION_REQUIRED');
    }
  }finally{if(safeCleanup)await h.cleanup();}
},60000);
