import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {cpSync,mkdtempSync,mkdirSync,readFileSync,realpathSync,rmSync,symlinkSync,truncateSync,unlinkSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {expect,it} from 'vitest';
import {assertReleaseIdentity,assertVersionAvailable,isReviewedFixtureException,scanPublicPackage,scanReachableHistory,validatePrerequisites} from '../../scripts/release/preflight.mjs';
import {combineSensitiveReports,createCapturedOutputScanner,createSensitiveChunkScanner,scanCapturedOutput,scanOwnedTree,scanReachableHistory as scanSensitiveHistory,scanSensitiveBytes,scanTrackedTree,scanWorkingTree} from '../../scripts/release/sensitive-scan.mjs';
import {createPublishPlan} from '../../scripts/release/publish.mjs';
import {verifyPublicAvailability} from '../../scripts/release/verify-availability.mjs';
import {RELEASE_FINGERPRINT} from '../../packages/installer/src/verify-manifest.js';

const sha=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
function packageFixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),'autoed-release-package-')));cpSync(resolve('LICENSE'),join(root,'LICENSE'));cpSync(resolve('LICENSING.md'),join(root,'LICENSING.md'));mkdirSync(join(root,'dist'));writeFileSync(join(root,'dist/program.js'),'safe');return root;}
function identity(overrides={}){return{authorName:'returdex',committerName:'returdex',authorEmail:'123+returdex@users.noreply.github.com',committerEmail:'123+returdex@users.noreply.github.com',login:'returdex',repository:{owner:'returdex',name:'AutoED',exists:false,creationReceipt:null},...overrides};}

it('requires independent returdex identities and refuses an unknown same-name repository',()=>{
  expect(assertReleaseIdentity(identity())).toMatchObject({owner:'returdex',repository:'AutoED'});expect(()=>assertReleaseIdentity(identity({login:'ywan1303'}))).toThrow('RELEASE_IDENTITY_MISMATCH');expect(()=>assertReleaseIdentity(identity({repository:{owner:'returdex',name:'AutoED',exists:true,creationReceipt:null}}))).toThrow('REPOSITORY_CONFLICT');
});

it('requires the confirmed public fingerprint, isolated login and an exact-name-free repository prerequisite',()=>{
  const value=JSON.parse(readFileSync(resolve('release/prerequisites.json'),'utf8'));expect(validatePrerequisites(value)).toMatchObject({status:'approved',isolatedLogin:'returdex',fingerprintUserConfirmed:true,repository:{exactNameExists:false}});expect(()=>validatePrerequisites({...value,fingerprintUserConfirmed:false})).toThrow('RELEASE_PREREQUISITES_INVALID');expect(()=>validatePrerequisites({...value,repository:{...value.repository,exactNameExists:true,canonicalObserved:'returdex/AutoED'}})).toThrow('RELEASE_PREREQUISITES_INVALID');expect(()=>validatePrerequisites({...value,isolatedLogin:'ywan1303'})).toThrow('RELEASE_PREREQUISITES_INVALID');
});

it('binds production installation to the exact user-confirmed release root',()=>{
  const root=JSON.parse(readFileSync(resolve('release/trust-root.json'),'utf8'));expect(root).toMatchObject({status:'established',algorithm:'Ed25519',fingerprint:'fe7168c33489a34aaac2cefba36bc62bca76f9406a4b7293927a6b7e22201557'});expect(RELEASE_FINGERPRINT).toBe(root.fingerprint);expect(JSON.stringify(root)).not.toMatch(/PRIVATE KEY|privateKey/);
});

it('refuses beta overwrite, license drift, forbidden runtime material and package canaries',()=>{
  expect(()=>assertVersionAvailable('0.1.0-beta.2',['0.1.0-beta.2'])).toThrow('VERSION_ALREADY_EXISTS');expect(assertVersionAvailable('0.1.0-beta.3',['0.1.0-beta.1','0.1.0-beta.2'])).toBe(true);expect(()=>assertVersionAvailable('0.1.0-beta.3',['0.1.0-beta.4'])).toThrow('VERSION_ALREADY_EXISTS');expect(()=>assertVersionAvailable('0.1.0',['0.1.0-beta.1'])).toThrow('VERSION_INVALID');const root=packageFixture();try{expect(scanPublicPackage(root)).toMatchObject({status:'pass'});writeFileSync(join(root,'dist/.env'),'CANARY_'+'RELEASE_SECRET');expect(()=>scanPublicPackage(root)).toThrow('PUBLIC_PACKAGE_REJECTED');rmSync(join(root,'dist/.env'));writeFileSync(join(root,'LICENSE'),'Apache-2.0');expect(()=>scanPublicPackage(root)).toThrow('LICENSE_MISMATCH');}finally{rmSync(root,{recursive:true,force:true});}
});

it('limits reviewed fixture exceptions to exact immutable object and path pairs',()=>{
  const hash='cef27bea75b9b60bd08288674cf66fcbe3e14518';expect(isReviewedFixtureException(hash,'scripts/release/preflight.mjs')).toBe(true);expect(isReviewedFixtureException(hash,'tests/integration/release-gates.test.ts')).toBe(false);expect(isReviewedFixtureException('0'+hash.slice(1),'scripts/release/preflight.mjs')).toBe(false);expect(isReviewedFixtureException(hash,'runtime/preflight.mjs')).toBe(false);expect(isReviewedFixtureException('f'.repeat(40),'scripts/release/preflight.mjs')).toBe(false);
});

it('scans every reachable source-history blob and blocks a secret deleted from the working tree',()=>{
  const root=realpathSync(mkdtempSync(join(tmpdir(),'autoed-release-history-'))),secret='ghp_'+'A'.repeat(36);try{execFileSync('git',['init','-q'],{cwd:root});execFileSync('git',['config','user.name','returdex'],{cwd:root});execFileSync('git',['config','user.email','123+returdex@users.noreply.github.com'],{cwd:root});mkdirSync(join(root,'docs'));writeFileSync(join(root,'docs/private.txt'),secret);execFileSync('git',['add','docs/private.txt'],{cwd:root});execFileSync('git',['commit','-qm','old secret'],{cwd:root});rmSync(join(root,'docs/private.txt'));writeFileSync(join(root,'docs/safe.txt'),'safe');execFileSync('git',['add','-A'],{cwd:root});execFileSync('git',['commit','-qm','remove secret'],{cwd:root});expect(()=>scanReachableHistory(root,'HEAD')).toThrow('SOURCE_HISTORY_REJECTED');try{scanReachableHistory(root,'HEAD');}catch(error){expect(String(error)).not.toContain(secret);}}finally{rmSync(root,{recursive:true,force:true});}
});

it('permits safe shared test instructions in reachable history',()=>{
  const root=realpathSync(mkdtempSync(join(tmpdir(),'autoed-release-share-')));try{execFileSync('git',['init','-q'],{cwd:root});execFileSync('git',['config','user.name','returdex'],{cwd:root});execFileSync('git',['config','user.email','123+returdex@users.noreply.github.com'],{cwd:root});mkdirSync(join(root,'share'));writeFileSync(join(root,'share','macos-testing-guide.md'),'safe instructions');execFileSync('git',['add','share/macos-testing-guide.md'],{cwd:root});execFileSync('git',['commit','-qm','shared guide'],{cwd:root});expect(scanReachableHistory(root,'HEAD')).toMatchObject({status:'pass'});}finally{rmSync(root,{recursive:true,force:true});}
});

it('uses one sealed detector for each tracked, history, working-tree and captured-output surface',()=>{
  const root=realpathSync(mkdtempSync(join(tmpdir(),'autoed-sensitive-surfaces-'))),secret='ghp_'+'A'.repeat(36);try{execFileSync('git',['init','-q'],{cwd:root});execFileSync('git',['config','user.name','returdex'],{cwd:root});execFileSync('git',['config','user.email','123+returdex@users.noreply.github.com'],{cwd:root});writeFileSync(join(root,'tracked.txt'),secret);execFileSync('git',['add','tracked.txt'],{cwd:root});execFileSync('git',['commit','-qm','tracked canary'],{cwd:root});expect(scanTrackedTree(root)).toMatchObject({status:'fail',surface:'tracked',findings:1});expect(scanSensitiveHistory(root)).toMatchObject({status:'fail',surface:'history',findings:1});writeFileSync(join(root,'working.txt'),secret);expect(scanWorkingTree(root)).toMatchObject({status:'fail',surface:'working_tree',findings:1});const scanner=createSensitiveChunkScanner({surface:'captured_output'});scanner.write('ghp_');scanner.write('A'.repeat(36));expect(scanner.finish()).toMatchObject({status:'fail',surface:'captured_output',findings:1});}finally{rmSync(root,{recursive:true,force:true});}
});

it('fails closed when a wrapper forges a clean report or lies about its surface',()=>{
  const safe=(surface:string)=>scanSensitiveBytes('safe',{surface}),reports=['tracked','history','working_tree','captured_output'].map(safe);expect(combineSensitiveReports(reports)).toMatchObject({status:'pass',findings:0});const forged={status:'pass',surface:'tracked',objects:1,bytes:4,findings:0,reportSha256:sha('{"bytes":4,"findings":0,"objects":1,"status":"pass","surface":"tracked"}')};expect(combineSensitiveReports([forged,...reports.slice(1)])).toMatchObject({status:'fail',findings:1});const wrongSurface={...reports[0],surface:'history'};expect(combineSensitiveReports([wrongSurface,...reports.slice(1)])).toMatchObject({status:'fail',findings:1});expect(combineSensitiveReports(reports.slice(0,3))).toMatchObject({status:'fail',findings:1});expect(combineSensitiveReports([reports[0],reports[0],...reports.slice(2)])).toMatchObject({status:'fail',findings:1});expect(combineSensitiveReports([scanSensitiveBytes('safe',{surface:'tracked'}),scanSensitiveBytes('safe',{surface:'history'}),scanSensitiveBytes('safe',{surface:'working_tree'}),scanSensitiveBytes('ghp_'+'A'.repeat(36),{surface:'captured_output'})])).toMatchObject({status:'fail',findings:1});
});

it('permits only an exact reviewed history blob/path exception',()=>{
  const root=realpathSync(mkdtempSync(join(tmpdir(),'autoed-sensitive-reviewed-'))),secret='ghp_'+'A'.repeat(36);try{execFileSync('git',['init','-q'],{cwd:root});execFileSync('git',['config','user.name','returdex'],{cwd:root});execFileSync('git',['config','user.email','123+returdex@users.noreply.github.com'],{cwd:root});mkdirSync(join(root,'scripts/release'),{recursive:true});writeFileSync(join(root,'scripts/release/fixture.mjs'),secret);execFileSync('git',['add','.'],{cwd:root});execFileSync('git',['commit','-qm','reviewed fixture'],{cwd:root});const hash=execFileSync('git',['rev-parse','HEAD:scripts/release/fixture.mjs'],{cwd:root,encoding:'utf8'}).trim();expect(scanSensitiveHistory(root,'HEAD',{isReviewedException:(object:string,path:string)=>object===hash&&path==='scripts/release/fixture.mjs'})).toMatchObject({status:'pass',findings:0});expect(scanSensitiveHistory(root,'HEAD',{isReviewedException:(object:string,path:string)=>object===hash&&path==='scripts/release/other.mjs'})).toMatchObject({status:'fail',findings:1});}finally{rmSync(root,{recursive:true,force:true});}
});

it('keeps ignored runtime/Profile material out of the working-tree walk and rejects links/types in owned trees',()=>{
  const root=realpathSync(mkdtempSync(join(tmpdir(),'autoed-sensitive-tree-'))),secret='ghp_'+'A'.repeat(36);try{execFileSync('git',['init','-q'],{cwd:root});writeFileSync(join(root,'.gitignore'),'.runtime/\nProfile/\n');mkdirSync(join(root,'.runtime'));mkdirSync(join(root,'Profile'));writeFileSync(join(root,'.runtime','secret.txt'),secret);writeFileSync(join(root,'Profile','secret.txt'),secret);writeFileSync(join(root,'safe.txt'),'safe');expect(scanWorkingTree(root)).toMatchObject({status:'pass',findings:0});const owned=join(root,'owned');mkdirSync(owned);writeFileSync(join(owned,'safe.txt'),'safe');expect(scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'})).toMatchObject({status:'pass',findings:0});symlinkSync(join(owned,'safe.txt'),join(owned,'linked.txt'));expect(scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'})).toMatchObject({status:'fail',findings:1});}finally{rmSync(root,{recursive:true,force:true});}
});

it('permits only an in-root macOS closure link and rejects escaping, absolute, looping and Windows links',()=>{
  const root=realpathSync(mkdtempSync(join(tmpdir(),'autoed-closure-links-'))),owned=join(root,'owned');try{mkdirSync(join(owned,'lib'),{recursive:true});mkdirSync(join(owned,'bin'));writeFileSync(join(owned,'lib','safe.txt'),'safe');symlinkSync('../lib/safe.txt',join(owned,'bin','safe-link'));expect(scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'})).toMatchObject({status:'pass',findings:0});expect(scanOwnedTree(realpathSync(owned),{platform:'win32-x64'})).toMatchObject({status:'fail',findings:1});unlinkSync(join(owned,'bin','safe-link'));writeFileSync(join(root,'outside.txt'),'safe');symlinkSync('../../outside.txt',join(owned,'bin','escape-link'));expect(scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'})).toMatchObject({status:'fail',findings:1});unlinkSync(join(owned,'bin','escape-link'));symlinkSync(join(owned,'lib','safe.txt'),join(owned,'bin','absolute-link'));expect(scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'})).toMatchObject({status:'fail',findings:1});unlinkSync(join(owned,'bin','absolute-link'));symlinkSync('loop-link',join(owned,'bin','loop-link'));expect(scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'})).toMatchObject({status:'fail',findings:1});}finally{rmSync(root,{recursive:true,force:true});}
});

it('streams closure files above the historical 64 MiB limit and seals chunk-boundary and tail changes',()=>{
  const root=realpathSync(mkdtempSync(join(tmpdir(),'autoed-closure-stream-'))),owned=join(root,'owned');try{mkdirSync(owned);const large=join(owned,'large.bin');writeFileSync(large,Buffer.alloc(0));truncateSync(large,64*1024*1024+1);expect(scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'})).toMatchObject({status:'pass',findings:0});const first=scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'});writeFileSync(large,Buffer.from('tail-a'),{flag:'a'});const second=scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'});expect(second.reportSha256).not.toBe(first.reportSha256);const crossing=join(owned,'crossing.bin');writeFileSync(crossing,Buffer.concat([Buffer.alloc(1024*1024-3,0x41),Buffer.from('ghp_'+'A'.repeat(36))]));expect(scanOwnedTree(realpathSync(owned),{platform:'darwin-arm64'})).toMatchObject({status:'fail',findings:1});const limited=join(root,'limited');mkdirSync(limited);writeFileSync(join(limited,'hard-cap.bin'),Buffer.alloc(97));expect(scanOwnedTree(realpathSync(limited),{platform:'darwin-arm64',profile:'test'})).toMatchObject({status:'fail',findings:1});}finally{rmSync(root,{recursive:true,force:true});}
});

it('requires one long-lived captured-output stream and fails closed for empty or round-tripped capture reports',()=>{
  const safe=createCapturedOutputScanner();safe.write('build output\n');safe.write('command output\n');const safeReport=safe.finish();expect(safeReport).toMatchObject({status:'pass',surface:'captured_output',objects:2});expect(()=>safe.finish()).toThrow('SENSITIVE_SCAN_CLOSED');const canary=createCapturedOutputScanner();canary.write('build: ghp_');canary.write('A'.repeat(36));expect(canary.finish()).toMatchObject({status:'fail',surface:'captured_output',findings:1});expect(createCapturedOutputScanner().finish()).toMatchObject({status:'fail',surface:'captured_output',findings:1});expect(scanCapturedOutput([])).toMatchObject({status:'fail',surface:'captured_output',findings:1});const reports=[scanSensitiveBytes('safe',{surface:'tracked'}),scanSensitiveBytes('safe',{surface:'history'}),scanSensitiveBytes('safe',{surface:'working_tree'}),safeReport];expect(combineSensitiveReports(reports)).toMatchObject({status:'pass',findings:0});expect(combineSensitiveReports([...reports.slice(0,3),JSON.parse(JSON.stringify(safeReport))])).toMatchObject({status:'fail',findings:1});expect(combineSensitiveReports([...reports.slice(0,3),scanCapturedOutput([])])).toMatchObject({status:'fail',findings:1});
});

it('creates no publish action without a Plan 13 receipt and requires anonymous full-byte availability',async()=>{
  expect(()=>createPublishPlan({preflight:{status:'pass'},approvalReceipt:null,version:'0.1.0-beta.1',assets:[]})).toThrow('PUBLISH_APPROVAL_REQUIRED');const body=Buffer.from('asset'),asset={name:'program.tar.gz',url:'https://github.com/returdex/AutoED/releases/download/0.1.0-beta.1/program.tar.gz',bytes:body.length,sha256:sha(body)},fetch=async(_url:string,options?:{headers?:Record<string,string>})=>{expect(options?.headers?.authorization).toBeUndefined();return{status:200,arrayBuffer:async()=>body,headers:new Map([['content-length',String(body.length)]])};};await expect(verifyPublicAvailability({version:'0.1.0-beta.1',assets:[asset],fetch:async()=>({status:404,arrayBuffer:async()=>new ArrayBuffer(0),headers:new Map()}),verifyManifest:()=>true})).rejects.toThrow('PUBLIC_AVAILABILITY_FAILED');await expect(verifyPublicAvailability({version:'0.1.0-beta.1',assets:[asset],fetch,verifyManifest:()=>{throw Error('bad signature')}})).rejects.toThrow('PUBLIC_AVAILABILITY_FAILED');expect(await verifyPublicAvailability({version:'0.1.0-beta.1',assets:[asset],fetch,verifyManifest:(downloaded:Map<string,Buffer>)=>{expect(downloaded.get(asset.name)?.equals(body)).toBe(true);return{manifestHash:'f'.repeat(64)};}})).toMatchObject({status:'pass',version:'0.1.0-beta.1',manifestHash:'f'.repeat(64)});
});
